# Generated by Django 4.1.4 on 2023-02-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0003_product_summoner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ban_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_banned',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
