# Generated by Django 4.1.4 on 2023-03-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0004_product_ban_reason_product_date_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='division',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], default=None, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_handleveled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.CharField(blank=True, choices=[('UNRANKED', 'Unranked'), ('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('MASTER', 'Master'), ('GRANDMASTER', 'Grandmaster'), ('CHALLENGER', 'Challenger')], default=None, max_length=32, null=True),
        ),
    ]
