# Generated by Django 4.1.4 on 2023-03-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0007_product_flash_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='losses',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wins',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
