# Generated by Django 4.1.4 on 2023-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0009_rename_losses_product_solo_losses_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['region'], name='lsb_product_region_d31e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discrete_level'], name='lsb_product_discret_c65317_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discrete_blue_essence'], name='lsb_product_discret_34ce33_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['orange_essence'], name='lsb_product_orange__8d47a7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rank'], name='lsb_product_rank_f05dec_idx'),
        ),
    ]
