# Generated by Django 4.2.1 on 2023-05-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0010_product_lsb_product_region_d31e5c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bare_metal',
            field=models.BooleanField(default=False),
        ),
    ]
