# Generated by Django 4.2.1 on 2023-06-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0012_product_city_product_date_sign_up_product_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='remarks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
