# Generated by Django 4.2.1 on 2023-06-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0014_product_date_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
