# Generated by Django 4.1.7 on 2023-07-18 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lsb", "0015_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="disabled_until",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
