# Generated by Django 4.1.7 on 2023-08-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lsb", "0017_remove_product_is_disabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UNRANKED", "Unranked"),
                    ("IRON", "Iron"),
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                    ("EMERALD", "Emerald"),
                    ("DIAMOND", "Diamond"),
                    ("MASTER", "Master"),
                    ("GRANDMASTER", "Grandmaster"),
                    ("CHALLENGER", "Challenger"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
