# Generated by Django 4.1.7 on 2023-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lsb", "0020_alter_product_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="region",
            field=models.CharField(
                choices=[
                    ("EUW", "EUW"),
                    ("EUNE", "EUNE"),
                    ("NA", "NA"),
                    ("OC1", "OCE"),
                    ("RU", "RU"),
                    ("TR", "TR"),
                    ("LA1", "LAN"),
                    ("LA2", "LAS"),
                    ("BR", "BR"),
                    ("JP", "JP"),
                    ("KR", "KR"),
                    ("PH2", "PH"),
                    ("SG2", "SG"),
                    ("TH2", "TH"),
                    ("TW2", "TW"),
                    ("VN2", "VN"),
                    ("PBE", "PBE"),
                ],
                default="EUW",
                max_length=4,
            ),
        ),
    ]
