# Generated by Django 4.1.7 on 2023-09-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lsb", "0021_alter_product_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="blue_essence",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="level",
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="mythic_essence",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="orange_essence",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
