# Generated by Django 4.1.7 on 2023-10-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lsb",
            "0022_alter_product_blue_essence_alter_product_level_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_proxmox",
            field=models.BooleanField(default=False),
        ),
    ]
