# Generated by Django 5.1.2 on 2024-12-07 04:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField()),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('backup_used', 'Backup Used')], default='initialized', max_length=16)),
                ('backup_codes', models.BinaryField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bc_attempts', models.IntegerField(default=0)),
                ('bc_timeout', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'axor_totp',
                'ordering': ['-created_at'],
            },
        ),
    ]
