# Generated by Django 5.1.2 on 2024-12-07 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('message', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField()),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('app_token_id', models.UUIDField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'axor_api_call_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
