# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enums_pb2 as enums__pb2
import preview_pb2 as preview__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x63tion.proto\x1a\x0b\x65nums.proto\x1a\rpreview.proto\"\x88\x03\n\x06\x41\x63tion\x12:\n\rswitch_active\x18\x01 \x01(\x0b\x32\x13.SwitchActiveActionH\x00R\x0cswitchActive\x12.\n\tplay_card\x18\x02 \x01(\x0b\x32\x0f.PlayCardActionH\x00R\x08playCard\x12.\n\tuse_skill\x18\x03 \x01(\x0b\x32\x0f.UseSkillActionH\x00R\x08useSkill\x12\x43\n\x10\x65lemental_tuning\x18\x04 \x01(\x0b\x32\x16.ElementalTuningActionH\x00R\x0f\x65lementalTuning\x12\x34\n\x0b\x64\x65\x63lare_end\x18\x05 \x01(\x0b\x32\x11.DeclareEndActionH\x00R\ndeclareEnd\x12&\n\x07preview\x18\n \x03(\x0b\x32\x0c.PreviewDataR\x07preview\x12\x35\n\rrequired_cost\x18\x0b \x03(\x0b\x32\x10.DiceRequirementR\x0crequiredCostB\x08\n\x06\x61\x63tion\"7\n\x12SwitchActiveAction\x12!\n\x0c\x63haracter_id\x18\x02 \x01(\x11R\x0b\x63haracterId\"H\n\x0ePlayCardAction\x12\x17\n\x07\x63\x61rd_id\x18\x02 \x01(\x11R\x06\x63\x61rdId\x12\x1d\n\ntarget_ids\x18\x03 \x03(\x11R\ttargetIds\"J\n\x0eUseSkillAction\x12\x19\n\x08skill_id\x18\x02 \x01(\x05R\x07skillId\x12\x1d\n\ntarget_ids\x18\x03 \x03(\x11R\ttargetIds\"k\n\x15\x45lementalTuningAction\x12&\n\x0fremoved_card_id\x18\x02 \x01(\x11R\rremovedCardId\x12*\n\x0btarget_dice\x18\x03 \x01(\x0e\x32\t.DiceTypeR\ntargetDice\"\x12\n\x10\x44\x65\x63lareEndActionB\x1d\x42\x0b\x41\x63tionProtoP\x01\xaa\x02\x0bGiTcg.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\013ActionProtoP\001\252\002\013GiTcg.Proto'
  _globals['_ACTION']._serialized_start=45
  _globals['_ACTION']._serialized_end=437
  _globals['_SWITCHACTIVEACTION']._serialized_start=439
  _globals['_SWITCHACTIVEACTION']._serialized_end=494
  _globals['_PLAYCARDACTION']._serialized_start=496
  _globals['_PLAYCARDACTION']._serialized_end=568
  _globals['_USESKILLACTION']._serialized_start=570
  _globals['_USESKILLACTION']._serialized_end=644
  _globals['_ELEMENTALTUNINGACTION']._serialized_start=646
  _globals['_ELEMENTALTUNINGACTION']._serialized_end=753
  _globals['_DECLAREENDACTION']._serialized_start=755
  _globals['_DECLAREENDACTION']._serialized_end=773
# @@protoc_insertion_point(module_scope)
