# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .actuator_disk_model import ActuatorDiskModel


@dataclass(kw_only=True)
class ActuatorDiskUniformThrust(ActuatorDiskModel):
    """Applies a uniform force at all locations on the disk"""

    thrust: float = 0.0
    "Thrust provided by the actuator disk"
