# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id


@dataclass(kw_only=True)
class BasicFluid(ParamGroupWrapper[clientpb.BasicFluid]):
    """Basic settings for a fluid flow physics solver."""

    viscous_model: enum.ViscousModel = enum.ViscousModel.RANS
    "Set the viscous model for the fluid solver."

    def _to_proto(self) -> clientpb.BasicFluid:
        _proto = clientpb.BasicFluid()
        _proto.viscous_model = self.viscous_model
        return _proto

    def _from_proto(self, proto: clientpb.BasicFluid) -> None:
        self.viscous_model = enum.ViscousModel(proto.viscous_model)
        return None
