# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .spalart_allmaras_boundary_conditions import SpalartAllmarasBoundaryConditions


@dataclass(kw_only=True)
class BcSaVariable(SpalartAllmarasBoundaryConditions):
    """Set the Spalart-Allmaras variable value at the boundary condition."""

    sa_variable: float = 4.166705541552236e-05
    "Uniform boundary condition value for the Spalart-Allmaras turbulence variable."
