# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .motion_type import MotionType


@dataclass(kw_only=True)
class ConstantTranslationMotion(MotionType):
    """Motion is defined by specifying an initial translation and constant translational velocity."""

    motion_formulation: enum.MotionFormulation = enum.MotionFormulation.AUTOMATIC_MOTION_FORMULATION
    "Formulation used to model motion of volumes in transient simulations."
    translation_velocity: Vector3 = field(default_factory=lambda: Vector3(0.0, 0.0, 0.0))
    "Constant translation velocity of this frame"
    translation: Vector3 = field(default_factory=lambda: Vector3(0.0, 0.0, 0.0))
    "Constant translation of this frame"
