# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .pseudo_time_step_method import PseudoTimeStepMethod


@dataclass(kw_only=True)
class FixedPseudoTimeStep(PseudoTimeStepMethod):
    """Apply a fixed pseudo time step."""

    pseudo_time_step: float = 1e-06
    "The fixed pseudo time step."
