# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .fluid_relaxation_method import FluidRelaxationMethod


@dataclass(kw_only=True)
class FluidExplicitRelaxation(FluidRelaxationMethod):
    """Apply an explicit relaxation scheme."""

    explicit_method: enum.ExplicitMethod = enum.ExplicitMethod.RK_4
    "Scheme for explicit relaxation or explicit time-accurate integration of the governing equations."
