# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .komega_initialization import KomegaInitialization


@dataclass(kw_only=True)
class InitTurbulentViscosityRatioAndIntensityKomega(KomegaInitialization):
    """Apply a uniform ratio of turbulent viscosity to laminar viscosity and turbulence intensity in the domain."""

    viscosity_ratio: float = 0.21043825715555026
    "Turbulent-to-laminar viscosity ratio."
    intensity: float = 0.05
    "Turbulence intensity."
