# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .outlet_strategy import OutletStrategy


@dataclass(kw_only=True)
class OutletTargetMassFlowRate(OutletStrategy):
    """Specify a target mass flow rate. Warning: this strategy will not work if the flow becomes choked or if it is fixed by any other flow constraint (e.g. a velocity inlet)."""

    pressure: float = 101325.0
    "Static pressure at the boundary relative to the material reference pressure. Also used as initial estimate to establish the target mass flow rate if requested."
    target_mass_flow_rate: float = 1.0
    "Target mass flow rate (or corrected mass flow rate)."
