
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-30T16:31:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0bb1a5341fe0fc10d7867fa0a991e624739c097",
 "version": "1.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
