tech_docs = [
            "Cloud Managed Services", "Super Cloud", "Hybrid Cloud", "Hybrid IaaS", "IaaS", "Infrastructure as a Service",
            "PaaS", "Platform as a Service", "Cloud", "Public Cloud", "Private Cloud", "Business Cloud", "Managed IaaS", "Managed Storage", 
            "Managed Services", "Storage as a Service", "Backup as a Service", "Compute as a Service", "DRaaS", "Disaster Recovery as a Service", 
            "BCaaS", "Business Continuity as a Service", "Cloud Provision", "Cloud Solutions", "Cloud Hosting", "Cloud Computing",
            "Managed Infrastructure as a Service", "Assured IaaS", "Elevate IaaS", "Official IaaS", "Official Sensitive IaaS", "Microsoft Azure", 
            "MS Azure", "Amazon Web Services", "AWS", "Office 365", "PSN Service Provider", "PSN SP", "PSN", "Managed Compute", "Managed Backup", 
            "Cloud Services", "Cloud Backup", "Cloud Security", "Cloud Technology", "Cloud Solutions", "Cloud Providers", "Data Lakes", "Cloud Database", 
            "Amazon Cloud", "Google Cloud", "Cloud Security", "Cloud Infrastructure", "Cloud Consulting", "Big Data", "Cloud Migrations", "Cloud Migration", 
            "Cloud Migrations", "Cloud Consulting", "Cloud Platform Migrations", "Assessments", "Cloud Discovery", "Cloud Assessment", 
            "Infrastructure Assessment", "System Discovery", "Cloud Optimisation", "Efficiency review", "Azure WAN", "Crown Hosting", 
            "On Premise to Teams", "File Shares to SharePoint Online", "Home Drive to OneDrive for Business", "File Shares to SharePoint Online", 
            "DFS to SharePoint Online", "Landing Zone", "Cloud Proof of Concept", "System Assessment", "Cloud Suitability", "AWS", "Amazon Web Services", 
            "Azure", "Public sector cloud", "Hybrid Cloud","Microsoft 365 and Office 365 Implementations", "Windows 10 Upgrades", 
            "Enterprise Mobility and Security", "Identity and Access Management", "Collaboration (Teams/SharePoint/OneDrive)", "Office 365", "O365", 
            "Office 365 Tenant", "Microsoft 365", "Microsoft 365 Tenant", "M365", "Office Online", "Exchange Online", "SharePoint Online", 
            "OneDrive for Business", "Azure Active Directory", "Office 365 Consultancy", "Office 365 Migration", "Windows 365", "Modern Workplace", 
            "Digital Workplace", "Evergreen IT", "Desktop as a Service", "Modern Management", "DLP", "Host Intrusion Prevention", "HIPs", 
            "Public Key Infrastructure", "PKI", "Certificate Services", "Anti-Spam", "Anti-Virus", "Anti-Malware", "Windows Defender", 
            "Windows Defender ATP", "MBAM", "Microsoft BitLocker Administration and Monitoring", "Web Content", "URL Content", "BitLocker", 
            "Disk Encryption""Windows 7", "Windows 8", "Windows 8.1", "Windows 10", "Windows 10 Migration", "Windows 10 Consultancy",
            "Windows 10 Enterprise", "Windows 10 Deployment", "Windows as a Service", "WaaS", "Windows Virtual Desktop", "Virtual Desktop", 
            "Mobile Device Management", "MDM", "Mobile Application Management", "MAM", "Unified Endpoint Management", "UEM", "Mobility as a Service", 
            "Enterprise Mobility and Security", "Microsoft EMS", "EMS", "Security and Compliance", "Security Compliance Package", "SCP", 
            "Identity and Access Management", "Identity Management", "IDAM", "System Center Configuration Manager", "Configuration Manager", "SCCM", 
            "WSUS", "Windows Servicing", "Current Branch", "Enterprise Mobility Server","Mobile Strategy", "Mobility for Business", 
            "System Center Endpoint Protection", "SCEP", "Data Loss Prevention", "Azure Information Protection", "Azure Sentinel", 
            "Removable Media Encryption", "Symantec Endpoint Protection", "Symantec Email Security.Cloud", "Symantec Email Image Control", 
            "Exchange Online Protection", "EOP", "Mimecast", "IronPort", "SMTP security", "Advanced Threat Protection", "ATP", "Advanced Data Governance",
            "Enterprise Mobility Management", "EMM", "Containerisation", "MaaS360", "Airwatch", "MobileIron", "Intune","Autopilot", "Device Provisioning", 
            "Device Deployment", "SOTI MobiControl", "VMware vRealise", "VMware vSphere", "VMware Workspace One", "VMware Horizon Cloud", 
            "Citrix XenMobile", "Citrix Workspace", "AppTec360", "Blackberry Enterprise Server", "BES", "Trend Micro", "Jamf Pro", 
            "Avalanche Mobility Center", "MobiLock Pro", "Hexnode", "Microsoft Teams", "PowerApps", "Power Apps", "Power Automate", "Microsoft Flow", 
            "Business Applications", "Azure B2B", "Azure Functions", "Azure Automation", "Records management", "Knowledge management", 
            "Auto-classification", "Project Cortex", "Labels", "Sensitivity labels", "Retention", "Retention labels", "Power Platform Centre of Excellence", 
            "Information architecture", "Teams Provisioning", "SharePoint Provisioning", "Starters / movers / leavers", "Employee onboarding", 
            "Business Process Automation", "Office 365 Governance", "Teams Governance", "Automation", "Adoption Planning", "Change Readiness Assessment", 
            "Adoption tracking", "Communications Planning", "Communications Templates", "Training Delivery", "Floorwalking", "Champions Network Mobilisation",
            "Benefit Realisation Planning", "Benefit Evaluation", "Business Engagement", "Artificial Intelligence Models", "AI Models", "AI Builder", "SPFx", 
            "Adaptive Card", "Fileshare Migrations", "SharePoint On-Premise", "SharePoint 2019", "SharePoint 2016", "SharePoint 2013", "SharePoint 2010", 
            "Infopath", "Access DB Migration", "Access database migration", "Power BI", "Teams Adoption", "End-user Adoption", "SharePoint workflows", 
            "Yammer", "Yammer Adoption", "Extranet", "SharePoint Support", "Office 365 Support", "Microsoft 365 Support", "Surface", "Microsoft Surface", 
            "Governance and Compliance", "Project Management", "Programme Management", "Portfolio Management", "Applications Packaging", 
            "Applications Rationalisation", "Deployment Planning", "Deployment Scheduling", "Service Transition Management", "Engagement Planning", 
            "Microsoft Information Protection", "MIP", "Project Cortex", "SharePoint Syntex", "Auto-Classification", "Auto-Classify", "Entity Extraction", 
            "Topic Experiences", "Content Understanding", "SharePoint Framework Azure Bot", "SIAM & Service Desk", "Service Integration and Management", 
            "ServiceDesk", "IT Service Management", "Managed IT Services", "IT Service Provider", "Cloud Managed Services", "Mobile Managed Services", 
            "Licence Management", "Baramundi", "Software asset management", "License management", "License compliance", "Mobile device management", 
            "Software audit", "Snow Software", "Effective license position", "License optimisation", "SAM", "Software maintenance", "Hardware maintenance", 
            "Software lifecycle", "Hardware lifecycle", "Outsource Full or Partial", "Field Engineering", "Networks / Telephony", "Application Support", 
            "ServiceDesk", "End User Computing", "End User Services", "IT Outsourcing", "IT Support Services", "Outsourced IT Support", 
            "Outsourcing Solutions", "IT Service Outsourcing", "IT Consultancy", "Future Operating Model", "IT Consulting Services", 
            "NHS Digital Outsourcing", "NHS Informatics", "Informatics", "NHS Interoperability", "GP IT Consultancy", "GP IT Outsourcing", 
            "GP IT Cloud", "Primary Care Digital Solutions", "Primary Care IT", "Digital Support Services", "Modern Workplace", 
            "Information Communication Technology", "ICT", "ICT Managed Service", "Testing", "Functional Test", "Unit Test", "Dev Test", 
            "Development Test", "System Test", "System Integration Test", "SIT", "System Acceptance test", "SAT", "Application Test", 
            "Migration Test", "User Acceptance Test", "UAT", "Regression Test", "Non-Functional Test", "Service Test", "Service Acceptance Test", 
            "Operational Test", "Disaster Recovery Test", "Stress Test", "Load Test", "Security Test", "Defect Management", "Test-as-a-Service", 
            "Automation Test", "Test Principles", "Test Policy", "Testing-as-a-Service", "Accessibility Test", "Component Test", "Black Box Test", 
            "RBT", "Risk Based Test", "QA", "Quality Assurance", "OAT", "Operational Acceptance Test", "SIT", "System Integration Test", 
            "Test Automation", "Test Suite", "Smoke Test", "Sap Test", "Sanity Test", "Sanity Check", "Test Culture", "Business Process Test", 
            "Acceptance Criteria", "Test Acceptance Criteria", "DR", "DR Test", "Volume Test", "Performance Test", "Test Process", "Test Scripts", 
            "Test Strategy", "Test Framework", "Test Tools", "Transformation Consulting", "IT Strategy", "IT Operating Model", "Technology Roadmap", 
            "Strategic Roadmap", "IT Strategic Assessment", "Digital Transformation Strategy", "NHS Digital", "NHS Long Term Plan", "Interoperability", 
            "Digital Healthcare", "Digital Innovation", "Robotics", "Project Management", "IT Consulting", "Strategic Planning", "IT Governance", 
            "Strategy Definition", "Information Technology Roadmap", "Primary Care Transformation", "Secondary Care Transformation", 
            "Social Care Transformation", "HealthTech", "Healthcare Technology", "INTEROPen", "Strategic IT Management", "Digital Transformation", 
            "Managed IT Strategy", "IT Transformation Consulting", "Business Strategy Development", "Health and Social Care", 
            "Child Health Transformation", "Mental Health Transformation", "Digital Patient", "Workforce", "Productivity", "Target Operating Model", 
            "Nursing Homes", "LHCRE", "NHS Improvement", "General Practice", "GP IT Solutions", "Digital Health", "GDE", "Global Digital Exemplar", 
            "Local Health and Care Record", "FHIR", "HL7", "DICOM", "Medical Imaging", "Clinical Workforce", "Healthcare Delivery", "Connected Health", 
            "eHealth", "eHealth consulting", "Digital Patients", "Digital Outpatients", "Digital Health Records", "Digital Child Health", 
            "Digital Learning Solutions", "Harnessing Digital Technology", "Interoperability Toolkit", "Integrate Public Clouds", 
            "Empower the Digital Workspace", "Modernize Data Centres", "Virtualisation Management", "Business Continuity", "Disaster Recovery", 
            "Edge and Internet of Things", "IoT", "Improve Clinician Workflows", "Enable Patient Engagement", "Service design", "Service redesign", 
            "User design", "Customer journey mapping", "Service blueprinting", "Organisational Design", "Customer journey optimisation", "GDS", 
            "Service review", "Options analysis", "Financial sustainability", "Accelerator", "Digital accelerator", "Business change", 
            "Change management", "Business readiness", "Zero based design", "Zero based redesign", "Zero-based budgeting", "TOM design", 
            "Target Operating Model", "Standard operating model", "Culture change", "Digital culture", "Digital organisation", "User journey", 
            "User research", "User experience", "Strategy", "Strategic advisor", "Programme management", "Project management", "Business case", 
            "Customer service transformation", "Service transformation", "Business process reengineering", "BPR", "Operational planning", 
            "Organisational review", "Organisational redesign", "Alternative delivery model", "Transformation Partner", "Strategic Partner", 
            "Strategic Partnership", "Asset management", "Asset rationalisation", "Integrated Care Service", "ICS", "Benefits realisation", 
            "Partnership", "Demand Management", "Maturity Assessment", "Service review", "Service Transformation", "Customer Experience", 
            "Customer Portal", "Customer Platform", "Digital Portal", "Digital Platform", "CXM", "Channel platform", 
            "Microsoft Dynamics", "Dynamics 365", "Website development", "Drupal", "Digital transformation", "CRM", "Customer Relationship Management", 
            "Data Migration", "Data Analytics", "RPA", "Robotics", "Robotic Process Automation", "Process Automation", "Intelligent Automation", 
            "Artificial intelligence", "Machine Learning", "ERP", "Enterprise Resource Planning", "Finance System", "HR System", "Unit4", 
            "Workforce Management", "Out of hours call handling", "Out of hours telephone handling service", "OOH call handling", 
            "OOH telephone handling service", "Call handling", "Out of hours", "Resource Planning", "Workforce management system", "Contact Centre", 
            "Call Centre", "Data Services", "Data Analysis", "Data Analyses", "Data Analytic", "Analytics", "Data Strategy", "Data Science", 
            "Data Management", "Dataset", "Data Set", "Data Visualisation", "Data Visualization", "Data Product", "Data User", "Enterprise Analytics", 
            "Data Innovation", "Analytical Requirement", "Analytics Platform", "Analysis Platform", "Data Specification", "Data Schema", "Data Standard", 
            "Data Privacy", "Data Engineer", "Trend", "Insight", "Intelligence", "Business Intelligence", "Performance", "Performance Analysis", 
            "Performance Data", "Time Series", "Timeseries", "Data Model", "Data Platform", "Self Service Analytic", "Data Management", 
            "Data Architect", "Data Architecture", "Data Ethic", "Data Principle", "Analysis Tool", "Analytics Tool", "Reporting Tool", 
            "Information Governance", "Data Governance", "Data Warehouse", "Decision Science", "Statutory Data", "Statistical Data", "Data Source", 
            "Statistical Analysis", "Data Owner", "Data Protection", "Demand Model", "Data Lake", "Demand Forecast", "Forecast Demand", "Official Data", 
            "Data Link", "Unstructured Data", "Data Custodian", "Data Steward", "Augmented Analytic", "Adult social care", "Social Care technology", 
            "Care Technology", "Telecare", "Technology enabled Care"
            ]