class IterableNotSet(Exception):
    """`Iterable is set to None and cannot perform operations on it.`"""
    ...
class IterableIsNotSupported(Exception):
    """`Iterable is not of the type list or its derived form. It is also not a tuple. Additionaly, it might not be valid.`"""
    ...
class IterableHasUnsupportedTypeValues(Exception):
    """`Iterable has some values that are unsupported.`"""
    ...
class KeyPropertyDeleteError(Exception):
    """`Key Property cannot be deleted`"""
    ...
class ReversePropertyDeleteError(Exception):
    """`Reverse Property cannot be deleted`"""
    ...
class CountingSortError(Exception):
    """`Counting Sort takes Iterable[int] type values`"""
    ... 
class RadixSortError(Exception):
    """`Radix Sort takes Iterable[int] type values`"""
    ...
class TargetCannotBeFound(Exception):
    """`Target cannot be Found at any cost.`"""
    ...
class TargetNotSet(Exception):
    """`Target is not set.`"""
    ...