#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['vjer']

package_data = \
{'': ['*']}

install_requires = \
['BatCave',
 'bumpver',
 'junitparser',
 'flake8',
 'flake8-annotations',
 'flake8-pyproject',
 'flit',
 'mypy',
 'pylint',
 'unittest-xml-reporting']

extras_require = \
{'test': ['types-PyYAML', 'types-requests']}

entry_points = \
{'console_scripts': ['vjer = vjer.vjer:main']}

setup(name='vjer',
      version='37.0.0',
      description='Vjer CI/CD module.',
      author=None,
      author_email='"Jeffery G. Smith" <web@pobox.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='~=3.12',
     )
