"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from exfunc import utils
from exfunc.types import BaseModel
from typing import Optional


class ServerErrorData(BaseModel):
    message: Optional[str] = None
    r"""Error message string"""


class ServerError(Exception):
    r"""Server error response"""

    data: ServerErrorData

    def __init__(self, data: ServerErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ServerErrorData)
