
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-02T16:25:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "df9b190bc5f5a077e3710dcec222054d0a6b890c",
 "version": "1.9.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
