__built_time__        =  "built at Sat Jan  4 14:44:33 2025_CST"
__name__              =  "pyasd"
__version__           =  "0.1.3"
__author__            =  "Shunhong Zhang"
__author_email__      =  "zhangshunhong.pku@gmail.com"
__url__               =  "https://pypi.org/project/pyasd/"
__license__           =  "MIT LICENSE"
__platform__          =  "linux"
