CONFIG_EXTENSIONS = ".yml", ".yaml", ".json", ".py"

CONFIG_DEFAULT_BASENAME = "xrlint.config"
CONFIG_DEFAULT_FILENAMES = [
    f"{CONFIG_DEFAULT_BASENAME}.yaml",
    f"{CONFIG_DEFAULT_BASENAME}.json",
    f"{CONFIG_DEFAULT_BASENAME}.py",
]

DEFAULT_OUTPUT_FORMAT = "simple"
DEFAULT_MAX_WARNINGS = -1
