# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .agents_search_deployed_agents_request_search_item_operator_operator import (
    AgentsSearchDeployedAgentsRequestSearchItemOperatorOperator,
)
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AgentsSearchDeployedAgentsRequestSearchItemOperator(UniversalBaseModel):
    field: typing.Literal["name"] = "name"
    operator: AgentsSearchDeployedAgentsRequestSearchItemOperatorOperator
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
