# Generated by Django 4.1.4 on 2023-01-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0002_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summoner_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
