# Generated by Django 4.1.4 on 2023-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0005_product_division_product_is_handleveled_product_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_auth_error',
            field=models.BooleanField(default=False),
        ),
    ]
