# Generated by Django 4.1.4 on 2023-03-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0006_product_is_auth_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_key',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
