# Generated by Django 4.1.4 on 2023-03-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0008_product_losses_product_wins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='losses',
            new_name='solo_losses',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='wins',
            new_name='solo_wins',
        ),
    ]
