# Generated by Django 4.2.1 on 2023-06-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0013_product_is_disabled_product_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_checked',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
