# Generated by Django 4.1.7 on 2023-07-19 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lsb", "0016_product_disabled_until"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_disabled",
        ),
    ]
