# Generated by Django 4.1.7 on 2023-08-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lsb", "0018_alter_product_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_last_played",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
