# Generated by Django 4.1.7 on 2023-09-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lsb", "0019_product_date_last_played"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rank",
            field=models.CharField(
                choices=[
                    ("UNRANKED", "Unranked"),
                    ("IRON", "Iron"),
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                    ("EMERALD", "Emerald"),
                    ("DIAMOND", "Diamond"),
                    ("MASTER", "Master"),
                    ("GRANDMASTER", "Grandmaster"),
                    ("CHALLENGER", "Challenger"),
                ],
                default="UNRANKED",
                max_length=32,
            ),
        ),
    ]
