# Generated by Django 4.1.4 on 2023-11-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0023_product_is_proxmox'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_safe',
            field=models.BooleanField(default=False),
        ),
    ]
