# Generated by Django 4.1.4 on 2023-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0025_alter_product_is_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_by',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
