# Generated by Django 4.1.7 on 2024-03-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0026_product_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_aram_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recovery_requested',
            field=models.BooleanField(default=True),
        ),
    ]
