# Generated by Django 4.1.7 on 2024-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0027_product_is_aram_only_product_is_recovery_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_recovery_requested',
            field=models.BooleanField(default=False),
        ),
    ]
