# Generated by Django 4.1.7 on 2024-06-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0028_alter_product_is_recovery_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_current_season_rank',
            field=models.BooleanField(default=True),
        ),
    ]
