# Generated by Django 4.1.7 on 2024-07-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lsb", "0029_product_is_current_season_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_password_checked",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
