# Generated by Django 4.1.7 on 2024-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0030_product_date_password_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quickplay_losses',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quickplay_wins',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
