# Generated by Django 4.2.16 on 2024-10-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0031_product_quickplay_losses_product_quickplay_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='region',
            field=models.CharField(choices=[('EUW', 'EUW'), ('EUNE', 'EUNE'), ('NA', 'NA'), ('OC1', 'OCE'), ('RU', 'RU'), ('TR', 'TR'), ('LA1', 'LAN'), ('LA2', 'LAS'), ('BR', 'BR'), ('JP', 'JP'), ('KR', 'KR'), ('PH2', 'PH'), ('SG2', 'SG'), ('TH2', 'TH'), ('TW2', 'TW'), ('VN2', 'VN'), ('PBE', 'PBE'), ('MENA', 'MENA')], default='EUW', max_length=4),
        ),
        migrations.AlterField(
            model_name='skin',
            name='tier',
            field=models.CharField(choices=[('ULTIMATE', 'Ultimate'), ('MYTHIC', 'Mythic'), ('LEGENDARY', 'Legendary'), ('EPIC', 'Epic'), ('STANDARD', 'Standard'), ('BUDGET', 'Budget'), ('LIMITED', 'Limited'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=9),
        ),
    ]
