# Generated by Django 4.2.17 on 2025-01-02 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsb', '0032_alter_product_region_alter_skin_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='honor_level',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
