__title__ = "cookiesparser"
__description__ = "cookiesparser is a mini module for parsing cookies."
__url__ = "https://github.com/farhanaliofficial/cookiesparser"
__version__ = "1.4.0"
__author__ = "Farhan Ali"
__author_email__ = "i.farhanali.dev@gmail.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright Farhan Ali"
