
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-03T17:31:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c33241297748f409a358ceeddf155f40084b6c3a",
 "version": "2025.1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
