
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-30T22:24:19-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e6f88322698f87cc2b495c370110bf46143cfa1",
 "version": "3.1.11.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
