
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-30T15:48:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1413c17aa53989e3ebe7cde09b387e74643c71d",
 "version": "3.0.0-beta.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
