
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-02T09:11:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "489cfdcd9dec993ed689fb17418fe54b12a69c87",
 "version": "1.6.2.post0.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
