import setuptools

# This file is auto-generated. Do not modify it manually.
# Generated by pyproject-to-setup converter

# Build isolation is enabled by default.
# Use --no-build-isolation flag with pip if needed.

setuptools.setup(
    name="spam-eggs",
    version="2020.0.0",
    python_requires=">=3.8",
    install_requires=[
        "httpx",
        "gidgethub[httpx]>4.0.0",
        "django>2.1; os_name != 'nt'",
        "django>2.0; os_name == 'nt'",
    ],
    extras_require={"gui": ["PyQt5"], "cli": ["rich", "click"]},
    entry_points={
        "console_scripts": ["spam-cli = spam:main_cli"],
        "gui_scripts": ["spam-gui = spam:main_gui"],
    },
    project_urls={
        "Homepage": "https://example.com",
        "Documentation": "https://readthedocs.org",
        "Repository": "https://github.com/me/spam.git",
        "Bug Tracker": "https://github.com/me/spam/issues",
        "Changelog": "https://github.com/me/spam/blob/master/CHANGELOG.md",
    },
    url="https://example.com",
)
