"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 28, 1, '', 'google/cloud/tpu/v2alpha1/cloud_tpu.proto')
_sym_db = _symbol_database.Default()
from .....google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from .....google.api import client_pb2 as google_dot_api_dot_client__pb2
from .....google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from .....google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from .....google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from .....google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
from .....google.type import interval_pb2 as google_dot_type_dot_interval__pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)google/cloud/tpu/v2alpha1/cloud_tpu.proto\x12\x19google.cloud.tpu.v2alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a#google/longrunning/operations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/rpc/status.proto\x1a\x1agoogle/type/interval.proto"k\n\x0fGuestAttributes\x12\x12\n\nquery_path\x18\x01 \x01(\t\x12D\n\x0bquery_value\x18\x02 \x01(\x0b2/.google.cloud.tpu.v2alpha1.GuestAttributesValue"V\n\x14GuestAttributesValue\x12>\n\x05items\x18\x01 \x03(\x0b2/.google.cloud.tpu.v2alpha1.GuestAttributesEntry"E\n\x14GuestAttributesEntry\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t"\xa9\x01\n\x0cAttachedDisk\x12\x13\n\x0bsource_disk\x18\x03 \x01(\t\x12>\n\x04mode\x18\x04 \x01(\x0e20.google.cloud.tpu.v2alpha1.AttachedDisk.DiskMode"D\n\x08DiskMode\x12\x19\n\x15DISK_MODE_UNSPECIFIED\x10\x00\x12\x0e\n\nREAD_WRITE\x10\x01\x12\r\n\tREAD_ONLY\x10\x02"9\n\x10SchedulingConfig\x12\x13\n\x0bpreemptible\x18\x01 \x01(\x08\x12\x10\n\x08reserved\x18\x02 \x01(\x08"s\n\x0fNetworkEndpoint\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12>\n\raccess_config\x18\x05 \x01(\x0b2\'.google.cloud.tpu.v2alpha1.AccessConfig"(\n\x0cAccessConfig\x12\x18\n\x0bexternal_ip\x18\x01 \x01(\tB\x03\xe0A\x03"i\n\rNetworkConfig\x12\x0f\n\x07network\x18\x01 \x01(\t\x12\x12\n\nsubnetwork\x18\x02 \x01(\t\x12\x1b\n\x13enable_external_ips\x18\x03 \x01(\x08\x12\x16\n\x0ecan_ip_forward\x18\x04 \x01(\x08".\n\x0eServiceAccount\x12\r\n\x05email\x18\x01 \x01(\t\x12\r\n\x05scope\x18\x02 \x03(\t"\xbb\x0e\n\x04Node\x12\x14\n\x04name\x18\x01 \x01(\tB\x06\xe0A\x03\xe0A\x05\x12\x13\n\x0bdescription\x18\x03 \x01(\t\x12\x18\n\x10accelerator_type\x18\x05 \x01(\t\x129\n\x05state\x18\t \x01(\x0e2%.google.cloud.tpu.v2alpha1.Node.StateB\x03\xe0A\x03\x12\x1f\n\x12health_description\x18\n \x01(\tB\x03\xe0A\x03\x12\x1c\n\x0fruntime_version\x18\x0b \x01(\tB\x03\xe0A\x02\x12@\n\x0enetwork_config\x18$ \x01(\x0b2(.google.cloud.tpu.v2alpha1.NetworkConfig\x12\x12\n\ncidr_block\x18\r \x01(\t\x12B\n\x0fservice_account\x18% \x01(\x0b2).google.cloud.tpu.v2alpha1.ServiceAccount\x124\n\x0bcreate_time\x18\x10 \x01(\x0b2\x1a.google.protobuf.TimestampB\x03\xe0A\x03\x12F\n\x11scheduling_config\x18\x11 \x01(\x0b2+.google.cloud.tpu.v2alpha1.SchedulingConfig\x12J\n\x11network_endpoints\x18\x15 \x03(\x0b2*.google.cloud.tpu.v2alpha1.NetworkEndpointB\x03\xe0A\x03\x126\n\x06health\x18\x16 \x01(\x0e2&.google.cloud.tpu.v2alpha1.Node.Health\x12;\n\x06labels\x18\x18 \x03(\x0b2+.google.cloud.tpu.v2alpha1.Node.LabelsEntry\x12?\n\x08metadata\x18" \x03(\x0b2-.google.cloud.tpu.v2alpha1.Node.MetadataEntry\x12\x0c\n\x04tags\x18( \x03(\t\x12\x0f\n\x02id\x18! \x01(\x03B\x03\xe0A\x03\x12;\n\ndata_disks\x18) \x03(\x0b2\'.google.cloud.tpu.v2alpha1.AttachedDisk\x12D\n\x0bapi_version\x18& \x01(\x0e2*.google.cloud.tpu.v2alpha1.Node.ApiVersionB\x03\xe0A\x03\x129\n\x08symptoms\x18\' \x03(\x0b2".google.cloud.tpu.v2alpha1.SymptomB\x03\xe0A\x03\x12\x1c\n\x0fqueued_resource\x18+ \x01(\tB\x03\xe0A\x03\x12H\n\x12accelerator_config\x18, \x01(\x0b2,.google.cloud.tpu.v2alpha1.AcceleratorConfig\x12S\n\x18shielded_instance_config\x18- \x01(\x0b21.google.cloud.tpu.v2alpha1.ShieldedInstanceConfig\x12\x1c\n\x0fmultislice_node\x18/ \x01(\x08B\x03\xe0A\x03\x12H\n\x10boot_disk_config\x181 \x01(\x0b2).google.cloud.tpu.v2alpha1.BootDiskConfigB\x03\xe0A\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x028\x01"\xe1\x01\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0e\n\nRESTARTING\x10\x03\x12\r\n\tREIMAGING\x10\x04\x12\x0c\n\x08DELETING\x10\x05\x12\r\n\tREPAIRING\x10\x06\x12\x0b\n\x07STOPPED\x10\x08\x12\x0c\n\x08STOPPING\x10\t\x12\x0c\n\x08STARTING\x10\n\x12\r\n\tPREEMPTED\x10\x0b\x12\x0e\n\nTERMINATED\x10\x0c\x12\n\n\x06HIDING\x10\r\x12\n\n\x06HIDDEN\x10\x0e\x12\x0c\n\x08UNHIDING\x10\x0f"o\n\x06Health\x12\x16\n\x12HEALTH_UNSPECIFIED\x10\x00\x12\x0b\n\x07HEALTHY\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x03\x12\x18\n\x14UNHEALTHY_TENSORFLOW\x10\x04\x12\x19\n\x15UNHEALTHY_MAINTENANCE\x10\x05"O\n\nApiVersion\x12\x1b\n\x17API_VERSION_UNSPECIFIED\x10\x00\x12\r\n\tV1_ALPHA1\x10\x01\x12\x06\n\x02V1\x10\x02\x12\r\n\tV2_ALPHA1\x10\x03:R\xeaAO\n\x17tpu.googleapis.com/Node\x124projects/{project}/locations/{location}/nodes/{node}"\xbd\x0b\n\x0eQueuedResource\x12\x14\n\x04name\x18\x01 \x01(\tB\x06\xe0A\x03\xe0A\x05\x12<\n\x03tpu\x18\x02 \x01(\x0b2-.google.cloud.tpu.v2alpha1.QueuedResource.TpuH\x00\x12K\n\x0bbest_effort\x18\x03 \x01(\x0b24.google.cloud.tpu.v2alpha1.QueuedResource.BestEffortH\x01\x12J\n\nguaranteed\x18\x04 \x01(\x0b24.google.cloud.tpu.v2alpha1.QueuedResource.GuaranteedH\x01\x12C\n\x04spot\x18\t \x01(\x0b2..google.cloud.tpu.v2alpha1.QueuedResource.SpotB\x03\xe0A\x01H\x01\x12Q\n\x0fqueueing_policy\x18\x05 \x01(\x0b28.google.cloud.tpu.v2alpha1.QueuedResource.QueueingPolicy\x12B\n\x05state\x18\x06 \x01(\x0b2..google.cloud.tpu.v2alpha1.QueuedResourceStateB\x03\xe0A\x03\x12\x18\n\x10reservation_name\x18\x08 \x01(\t\x1a\x89\x03\n\x03Tpu\x12I\n\tnode_spec\x18\x01 \x03(\x0b26.google.cloud.tpu.v2alpha1.QueuedResource.Tpu.NodeSpec\x1a\xb6\x02\n\x08NodeSpec\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12f\n\x11multi_node_params\x18\x06 \x01(\x0b2F.google.cloud.tpu.v2alpha1.QueuedResource.Tpu.NodeSpec.MultiNodeParamsB\x03\xe0A\x01\x122\n\x04node\x18\x03 \x01(\x0b2\x1f.google.cloud.tpu.v2alpha1.NodeB\x03\xe0A\x02\x1aB\n\x0fMultiNodeParams\x12\x17\n\nnode_count\x18\x01 \x01(\x05B\x03\xe0A\x02\x12\x16\n\x0enode_id_prefix\x18\x02 \x01(\t\x1a\x0c\n\nBestEffort\x1a\x06\n\x04Spot\x1aY\n\nGuaranteed\x124\n\x0cmin_duration\x18\x01 \x01(\x0b2\x19.google.protobuf.DurationB\x03\xe0A\x01\x12\x15\n\x08reserved\x18\x02 \x01(\x08B\x03\xe0A\x01\x1a\xc3\x02\n\x0eQueueingPolicy\x129\n\x14valid_until_duration\x18\x01 \x01(\x0b2\x19.google.protobuf.DurationH\x00\x126\n\x10valid_until_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.TimestampH\x00\x129\n\x14valid_after_duration\x18\x03 \x01(\x0b2\x19.google.protobuf.DurationH\x00\x126\n\x10valid_after_time\x18\x04 \x01(\x0b2\x1a.google.protobuf.TimestampH\x00\x12/\n\x0evalid_interval\x18\x05 \x01(\x0b2\x15.google.type.IntervalH\x00B\x1a\n\x18start_timing_constraints:q\xeaAn\n!tpu.googleapis.com/QueuedResource\x12Iprojects/{project}/locations/{location}/queuedResources/{queued_resource}B\n\n\x08resourceB\x06\n\x04tier"\x9a\n\n\x13QueuedResourceState\x12C\n\x05state\x18\x01 \x01(\x0e24.google.cloud.tpu.v2alpha1.QueuedResourceState.State\x12T\n\rcreating_data\x18\x02 \x01(\x0b2;.google.cloud.tpu.v2alpha1.QueuedResourceState.CreatingDataH\x00\x12T\n\raccepted_data\x18\x03 \x01(\x0b2;.google.cloud.tpu.v2alpha1.QueuedResourceState.AcceptedDataH\x00\x12\\\n\x11provisioning_data\x18\x04 \x01(\x0b2?.google.cloud.tpu.v2alpha1.QueuedResourceState.ProvisioningDataH\x00\x12P\n\x0bfailed_data\x18\x05 \x01(\x0b29.google.cloud.tpu.v2alpha1.QueuedResourceState.FailedDataH\x00\x12T\n\rdeleting_data\x18\x06 \x01(\x0b2;.google.cloud.tpu.v2alpha1.QueuedResourceState.DeletingDataH\x00\x12P\n\x0bactive_data\x18\x07 \x01(\x0b29.google.cloud.tpu.v2alpha1.QueuedResourceState.ActiveDataH\x00\x12X\n\x0fsuspending_data\x18\x08 \x01(\x0b2=.google.cloud.tpu.v2alpha1.QueuedResourceState.SuspendingDataH\x00\x12V\n\x0esuspended_data\x18\t \x01(\x0b2<.google.cloud.tpu.v2alpha1.QueuedResourceState.SuspendedDataH\x00\x12[\n\x0fstate_initiator\x18\n \x01(\x0e2=.google.cloud.tpu.v2alpha1.QueuedResourceState.StateInitiatorB\x03\xe0A\x03\x1a\x0e\n\x0cCreatingData\x1a\x0e\n\x0cAcceptedData\x1a\x12\n\x10ProvisioningData\x1a/\n\nFailedData\x12!\n\x05error\x18\x01 \x01(\x0b2\x12.google.rpc.Status\x1a\x0e\n\x0cDeletingData\x1a\x0c\n\nActiveData\x1a\x10\n\x0eSuspendingData\x1a\x0f\n\rSuspendedData"\xac\x01\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08CREATING\x10\x01\x12\x0c\n\x08ACCEPTED\x10\x02\x12\x10\n\x0cPROVISIONING\x10\x03\x12\n\n\x06FAILED\x10\x04\x12\x0c\n\x08DELETING\x10\x05\x12\n\n\x06ACTIVE\x10\x06\x12\x0e\n\nSUSPENDING\x10\x07\x12\r\n\tSUSPENDED\x10\x08\x12\x19\n\x15WAITING_FOR_RESOURCES\x10\t"H\n\x0eStateInitiator\x12\x1f\n\x1bSTATE_INITIATOR_UNSPECIFIED\x10\x00\x12\x08\n\x04USER\x10\x01\x12\x0b\n\x07SERVICE\x10\x02B\x0c\n\nstate_data"j\n\x10ListNodesRequest\x12/\n\x06parent\x18\x01 \x01(\tB\x1f\xe0A\x02\xfaA\x19\x12\x17tpu.googleapis.com/Node\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"q\n\x11ListNodesResponse\x12.\n\x05nodes\x18\x01 \x03(\x0b2\x1f.google.cloud.tpu.v2alpha1.Node\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"?\n\x0eGetNodeRequest\x12-\n\x04name\x18\x01 \x01(\tB\x1f\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node"\xa7\x01\n\x11CreateNodeRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x122\n\x04node\x18\x03 \x01(\x0b2\x1f.google.cloud.tpu.v2alpha1.NodeB\x03\xe0A\x02\x12\x12\n\nrequest_id\x18\x06 \x01(\t"V\n\x11DeleteNodeRequest\x12-\n\x04name\x18\x01 \x01(\tB\x1f\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node\x12\x12\n\nrequest_id\x18\x03 \x01(\t"@\n\x0fStopNodeRequest\x12-\n\x04name\x18\x01 \x01(\tB\x1f\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node"A\n\x10StartNodeRequest\x12-\n\x04name\x18\x01 \x01(\tB\x1f\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node"}\n\x11UpdateNodeRequest\x124\n\x0bupdate_mask\x18\x01 \x01(\x0b2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02\x122\n\x04node\x18\x02 \x01(\x0b2\x1f.google.cloud.tpu.v2alpha1.NodeB\x03\xe0A\x02"~\n\x1aListQueuedResourcesRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\x12!tpu.googleapis.com/QueuedResource\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"\x90\x01\n\x1bListQueuedResourcesResponse\x12C\n\x10queued_resources\x18\x01 \x03(\x0b2).google.cloud.tpu.v2alpha1.QueuedResource\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"S\n\x18GetQueuedResourceRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!tpu.googleapis.com/QueuedResource"\xd1\x01\n\x1bCreateQueuedResourceRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location\x12\x1a\n\x12queued_resource_id\x18\x02 \x01(\t\x12G\n\x0fqueued_resource\x18\x03 \x01(\x0b2).google.cloud.tpu.v2alpha1.QueuedResourceB\x03\xe0A\x02\x12\x12\n\nrequest_id\x18\x04 \x01(\t"y\n\x1bDeleteQueuedResourceRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!tpu.googleapis.com/QueuedResource\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\r\n\x05force\x18\x03 \x01(\x08"U\n\x1aResetQueuedResourceRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!tpu.googleapis.com/QueuedResource" \n\x0fServiceIdentity\x12\r\n\x05email\x18\x01 \x01(\t"[\n\x1eGenerateServiceIdentityRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!locations.googleapis.com/Location"_\n\x1fGenerateServiceIdentityResponse\x12<\n\x08identity\x18\x01 \x01(\x0b2*.google.cloud.tpu.v2alpha1.ServiceIdentity"\xee\x01\n\x0fAcceleratorType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12I\n\x13accelerator_configs\x18\x03 \x03(\x0b2,.google.cloud.tpu.v2alpha1.AcceleratorConfig:t\xeaAq\n"tpu.googleapis.com/AcceleratorType\x12Kprojects/{project}/locations/{location}/acceleratorTypes/{accelerator_type}"U\n\x19GetAcceleratorTypeRequest\x128\n\x04name\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\n"tpu.googleapis.com/AcceleratorType"\xa2\x01\n\x1bListAcceleratorTypesRequest\x12:\n\x06parent\x18\x01 \x01(\tB*\xe0A\x02\xfaA$\x12"tpu.googleapis.com/AcceleratorType\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t\x12\x10\n\x08order_by\x18\x06 \x01(\t"\x93\x01\n\x1cListAcceleratorTypesResponse\x12E\n\x11accelerator_types\x18\x01 \x03(\x0b2*.google.cloud.tpu.v2alpha1.AcceleratorType\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xa2\x01\n\x0eRuntimeVersion\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t:q\xeaAn\n!tpu.googleapis.com/RuntimeVersion\x12Iprojects/{project}/locations/{location}/runtimeVersions/{runtime_version}"S\n\x18GetRuntimeVersionRequest\x127\n\x04name\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\n!tpu.googleapis.com/RuntimeVersion"\xa0\x01\n\x1aListRuntimeVersionsRequest\x129\n\x06parent\x18\x01 \x01(\tB)\xe0A\x02\xfaA#\x12!tpu.googleapis.com/RuntimeVersion\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\x12\x0e\n\x06filter\x18\x05 \x01(\t\x12\x10\n\x08order_by\x18\x06 \x01(\t"\x90\x01\n\x1bListRuntimeVersionsResponse\x12C\n\x10runtime_versions\x18\x01 \x03(\x0b2).google.cloud.tpu.v2alpha1.RuntimeVersion\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0bunreachable\x18\x03 \x03(\t"\xd6\x01\n\x11OperationMetadata\x12/\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12,\n\x08end_time\x18\x02 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0c\n\x04verb\x18\x04 \x01(\t\x12\x15\n\rstatus_detail\x18\x05 \x01(\t\x12\x18\n\x10cancel_requested\x18\x06 \x01(\x08\x12\x13\n\x0bapi_version\x18\x07 \x01(\t"\xcb\x02\n\x07Symptom\x12/\n\x0bcreate_time\x18\x01 \x01(\x0b2\x1a.google.protobuf.Timestamp\x12D\n\x0csymptom_type\x18\x02 \x01(\x0e2..google.cloud.tpu.v2alpha1.Symptom.SymptomType\x12\x0f\n\x07details\x18\x03 \x01(\t\x12\x11\n\tworker_id\x18\x04 \x01(\t"\xa4\x01\n\x0bSymptomType\x12\x1c\n\x18SYMPTOM_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n\nLOW_MEMORY\x10\x01\x12\x11\n\rOUT_OF_MEMORY\x10\x02\x12\x15\n\x11EXECUTE_TIMED_OUT\x10\x03\x12\x13\n\x0fMESH_BUILD_FAIL\x10\x04\x12\x15\n\x11HBM_OUT_OF_MEMORY\x10\x05\x12\x11\n\rPROJECT_ABUSE\x10\x06"r\n\x19GetGuestAttributesRequest\x12-\n\x04name\x18\x01 \x01(\tB\x1f\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node\x12\x12\n\nquery_path\x18\x02 \x01(\t\x12\x12\n\nworker_ids\x18\x03 \x03(\t"b\n\x1aGetGuestAttributesResponse\x12D\n\x10guest_attributes\x18\x01 \x03(\x0b2*.google.cloud.tpu.v2alpha1.GuestAttributes"d\n\x1fSimulateMaintenanceEventRequest\x12-\n\x04name\x18\x01 \x01(\tB\x1f\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node\x12\x12\n\nworker_ids\x18\x02 \x03(\t"\xa6\x01\n\x11AcceleratorConfig\x12D\n\x04type\x18\x01 \x01(\x0e21.google.cloud.tpu.v2alpha1.AcceleratorConfig.TypeB\x03\xe0A\x02\x12\x15\n\x08topology\x18\x02 \x01(\tB\x03\xe0A\x02"4\n\x04Type\x12\x14\n\x10TYPE_UNSPECIFIED\x10\x00\x12\x06\n\x02V2\x10\x02\x12\x06\n\x02V3\x10\x04\x12\x06\n\x02V4\x10\x07"4\n\x16ShieldedInstanceConfig\x12\x1a\n\x12enable_secure_boot\x18\x01 \x01(\x08"\x92\x01\n\x0eBootDiskConfig\x12V\n\x17customer_encryption_key\x18\x01 \x01(\x0b20.google.cloud.tpu.v2alpha1.CustomerEncryptionKeyB\x03\xe0A\x01\x12(\n\x1benable_confidential_compute\x18\x02 \x01(\x08B\x03\xe0A\x01"6\n\x15CustomerEncryptionKey\x12\x16\n\x0ckms_key_name\x18\x07 \x01(\tH\x00B\x05\n\x03key2\x9e\x1f\n\x03Tpu\x12\xa8\x01\n\tListNodes\x12+.google.cloud.tpu.v2alpha1.ListNodesRequest\x1a,.google.cloud.tpu.v2alpha1.ListNodesResponse"@\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v2alpha1/{parent=projects/*/locations/*}/nodes\x12\x95\x01\n\x07GetNode\x12).google.cloud.tpu.v2alpha1.GetNodeRequest\x1a\x1f.google.cloud.tpu.v2alpha1.Node">\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v2alpha1/{name=projects/*/locations/*/nodes/*}\x12\xca\x01\n\nCreateNode\x12,.google.cloud.tpu.v2alpha1.CreateNodeRequest\x1a\x1d.google.longrunning.Operation"o\xcaA\x19\n\x04Node\x12\x11OperationMetadata\xdaA\x13parent,node,node_id\x82\xd3\xe4\x93\x027"//v2alpha1/{parent=projects/*/locations/*}/nodes:\x04node\x12\xc6\x01\n\nDeleteNode\x12,.google.cloud.tpu.v2alpha1.DeleteNodeRequest\x1a\x1d.google.longrunning.Operation"k\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x021*//v2alpha1/{name=projects/*/locations/*/nodes/*}\x12\xb2\x01\n\x08StopNode\x12*.google.cloud.tpu.v2alpha1.StopNodeRequest\x1a\x1d.google.longrunning.Operation"[\xcaA\x19\n\x04Node\x12\x11OperationMetadata\x82\xd3\xe4\x93\x029"4/v2alpha1/{name=projects/*/locations/*/nodes/*}:stop:\x01*\x12\xb5\x01\n\tStartNode\x12+.google.cloud.tpu.v2alpha1.StartNodeRequest\x1a\x1d.google.longrunning.Operation"\\\xcaA\x19\n\x04Node\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02:"5/v2alpha1/{name=projects/*/locations/*/nodes/*}:start:\x01*\x12\xcc\x01\n\nUpdateNode\x12,.google.cloud.tpu.v2alpha1.UpdateNodeRequest\x1a\x1d.google.longrunning.Operation"q\xcaA\x19\n\x04Node\x12\x11OperationMetadata\xdaA\x10node,update_mask\x82\xd3\xe4\x93\x02<24/v2alpha1/{node.name=projects/*/locations/*/nodes/*}:\x04node\x12\xd0\x01\n\x13ListQueuedResources\x125.google.cloud.tpu.v2alpha1.ListQueuedResourcesRequest\x1a6.google.cloud.tpu.v2alpha1.ListQueuedResourcesResponse"J\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v2alpha1/{parent=projects/*/locations/*}/queuedResources\x12\xbd\x01\n\x11GetQueuedResource\x123.google.cloud.tpu.v2alpha1.GetQueuedResourceRequest\x1a).google.cloud.tpu.v2alpha1.QueuedResource"H\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v2alpha1/{name=projects/*/locations/*/queuedResources/*}\x12\x94\x02\n\x14CreateQueuedResource\x126.google.cloud.tpu.v2alpha1.CreateQueuedResourceRequest\x1a\x1d.google.longrunning.Operation"\xa4\x01\xcaA#\n\x0eQueuedResource\x12\x11OperationMetadata\xdaA)parent,queued_resource,queued_resource_id\x82\xd3\xe4\x93\x02L"9/v2alpha1/{parent=projects/*/locations/*}/queuedResources:\x0fqueued_resource\x12\xdd\x01\n\x14DeleteQueuedResource\x126.google.cloud.tpu.v2alpha1.DeleteQueuedResourceRequest\x1a\x1d.google.longrunning.Operation"n\xcaA#\n\x0eQueuedResource\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02;*9/v2alpha1/{name=projects/*/locations/*/queuedResources/*}\x12\xe4\x01\n\x13ResetQueuedResource\x125.google.cloud.tpu.v2alpha1.ResetQueuedResourceRequest\x1a\x1d.google.longrunning.Operation"w\xcaA#\n\x0eQueuedResource\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02D"?/v2alpha1/{name=projects/*/locations/*/queuedResources/*}:reset:\x01*\x12\xde\x01\n\x17GenerateServiceIdentity\x129.google.cloud.tpu.v2alpha1.GenerateServiceIdentityRequest\x1a:.google.cloud.tpu.v2alpha1.GenerateServiceIdentityResponse"L\x82\xd3\xe4\x93\x02F"A/v2alpha1/{parent=projects/*/locations/*}:generateServiceIdentity:\x01*\x12\xd4\x01\n\x14ListAcceleratorTypes\x126.google.cloud.tpu.v2alpha1.ListAcceleratorTypesRequest\x1a7.google.cloud.tpu.v2alpha1.ListAcceleratorTypesResponse"K\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v2alpha1/{parent=projects/*/locations/*}/acceleratorTypes\x12\xc1\x01\n\x12GetAcceleratorType\x124.google.cloud.tpu.v2alpha1.GetAcceleratorTypeRequest\x1a*.google.cloud.tpu.v2alpha1.AcceleratorType"I\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v2alpha1/{name=projects/*/locations/*/acceleratorTypes/*}\x12\xd0\x01\n\x13ListRuntimeVersions\x125.google.cloud.tpu.v2alpha1.ListRuntimeVersionsRequest\x1a6.google.cloud.tpu.v2alpha1.ListRuntimeVersionsResponse"J\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v2alpha1/{parent=projects/*/locations/*}/runtimeVersions\x12\xbd\x01\n\x11GetRuntimeVersion\x123.google.cloud.tpu.v2alpha1.GetRuntimeVersionRequest\x1a).google.cloud.tpu.v2alpha1.RuntimeVersion"H\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v2alpha1/{name=projects/*/locations/*/runtimeVersions/*}\x12\xd0\x01\n\x12GetGuestAttributes\x124.google.cloud.tpu.v2alpha1.GetGuestAttributesRequest\x1a5.google.cloud.tpu.v2alpha1.GetGuestAttributesResponse"M\x82\xd3\xe4\x93\x02G"B/v2alpha1/{name=projects/*/locations/*/nodes/*}:getGuestAttributes:\x01*\x12\xe6\x01\n\x18SimulateMaintenanceEvent\x12:.google.cloud.tpu.v2alpha1.SimulateMaintenanceEventRequest\x1a\x1d.google.longrunning.Operation"o\xcaA\x19\n\x04Node\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02M"H/v2alpha1/{name=projects/*/locations/*/nodes/*}:simulateMaintenanceEvent:\x01*\x1aF\xcaA\x12tpu.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformBa\n\x1dcom.google.cloud.tpu.v2alpha1B\rCloudTpuProtoP\x01Z/cloud.google.com/go/tpu/apiv2alpha1/tpupb;tpupbb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.cloud.tpu.v2alpha1.cloud_tpu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\n\x1dcom.google.cloud.tpu.v2alpha1B\rCloudTpuProtoP\x01Z/cloud.google.com/go/tpu/apiv2alpha1/tpupb;tpupb'
    _globals['_ACCESSCONFIG'].fields_by_name['external_ip']._loaded_options = None
    _globals['_ACCESSCONFIG'].fields_by_name['external_ip']._serialized_options = b'\xe0A\x03'
    _globals['_NODE_LABELSENTRY']._loaded_options = None
    _globals['_NODE_LABELSENTRY']._serialized_options = b'8\x01'
    _globals['_NODE_METADATAENTRY']._loaded_options = None
    _globals['_NODE_METADATAENTRY']._serialized_options = b'8\x01'
    _globals['_NODE'].fields_by_name['name']._loaded_options = None
    _globals['_NODE'].fields_by_name['name']._serialized_options = b'\xe0A\x03\xe0A\x05'
    _globals['_NODE'].fields_by_name['state']._loaded_options = None
    _globals['_NODE'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_NODE'].fields_by_name['health_description']._loaded_options = None
    _globals['_NODE'].fields_by_name['health_description']._serialized_options = b'\xe0A\x03'
    _globals['_NODE'].fields_by_name['runtime_version']._loaded_options = None
    _globals['_NODE'].fields_by_name['runtime_version']._serialized_options = b'\xe0A\x02'
    _globals['_NODE'].fields_by_name['create_time']._loaded_options = None
    _globals['_NODE'].fields_by_name['create_time']._serialized_options = b'\xe0A\x03'
    _globals['_NODE'].fields_by_name['network_endpoints']._loaded_options = None
    _globals['_NODE'].fields_by_name['network_endpoints']._serialized_options = b'\xe0A\x03'
    _globals['_NODE'].fields_by_name['id']._loaded_options = None
    _globals['_NODE'].fields_by_name['id']._serialized_options = b'\xe0A\x03'
    _globals['_NODE'].fields_by_name['api_version']._loaded_options = None
    _globals['_NODE'].fields_by_name['api_version']._serialized_options = b'\xe0A\x03'
    _globals['_NODE'].fields_by_name['symptoms']._loaded_options = None
    _globals['_NODE'].fields_by_name['symptoms']._serialized_options = b'\xe0A\x03'
    _globals['_NODE'].fields_by_name['queued_resource']._loaded_options = None
    _globals['_NODE'].fields_by_name['queued_resource']._serialized_options = b'\xe0A\x03'
    _globals['_NODE'].fields_by_name['multislice_node']._loaded_options = None
    _globals['_NODE'].fields_by_name['multislice_node']._serialized_options = b'\xe0A\x03'
    _globals['_NODE'].fields_by_name['boot_disk_config']._loaded_options = None
    _globals['_NODE'].fields_by_name['boot_disk_config']._serialized_options = b'\xe0A\x01'
    _globals['_NODE']._loaded_options = None
    _globals['_NODE']._serialized_options = b'\xeaAO\n\x17tpu.googleapis.com/Node\x124projects/{project}/locations/{location}/nodes/{node}'
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC_MULTINODEPARAMS'].fields_by_name['node_count']._loaded_options = None
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC_MULTINODEPARAMS'].fields_by_name['node_count']._serialized_options = b'\xe0A\x02'
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC'].fields_by_name['parent']._loaded_options = None
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC'].fields_by_name['multi_node_params']._loaded_options = None
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC'].fields_by_name['multi_node_params']._serialized_options = b'\xe0A\x01'
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC'].fields_by_name['node']._loaded_options = None
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC'].fields_by_name['node']._serialized_options = b'\xe0A\x02'
    _globals['_QUEUEDRESOURCE_GUARANTEED'].fields_by_name['min_duration']._loaded_options = None
    _globals['_QUEUEDRESOURCE_GUARANTEED'].fields_by_name['min_duration']._serialized_options = b'\xe0A\x01'
    _globals['_QUEUEDRESOURCE_GUARANTEED'].fields_by_name['reserved']._loaded_options = None
    _globals['_QUEUEDRESOURCE_GUARANTEED'].fields_by_name['reserved']._serialized_options = b'\xe0A\x01'
    _globals['_QUEUEDRESOURCE'].fields_by_name['name']._loaded_options = None
    _globals['_QUEUEDRESOURCE'].fields_by_name['name']._serialized_options = b'\xe0A\x03\xe0A\x05'
    _globals['_QUEUEDRESOURCE'].fields_by_name['spot']._loaded_options = None
    _globals['_QUEUEDRESOURCE'].fields_by_name['spot']._serialized_options = b'\xe0A\x01'
    _globals['_QUEUEDRESOURCE'].fields_by_name['state']._loaded_options = None
    _globals['_QUEUEDRESOURCE'].fields_by_name['state']._serialized_options = b'\xe0A\x03'
    _globals['_QUEUEDRESOURCE']._loaded_options = None
    _globals['_QUEUEDRESOURCE']._serialized_options = b'\xeaAn\n!tpu.googleapis.com/QueuedResource\x12Iprojects/{project}/locations/{location}/queuedResources/{queued_resource}'
    _globals['_QUEUEDRESOURCESTATE'].fields_by_name['state_initiator']._loaded_options = None
    _globals['_QUEUEDRESOURCESTATE'].fields_by_name['state_initiator']._serialized_options = b'\xe0A\x03'
    _globals['_LISTNODESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTNODESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA\x19\x12\x17tpu.googleapis.com/Node'
    _globals['_GETNODEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETNODEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node'
    _globals['_CREATENODEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATENODEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATENODEREQUEST'].fields_by_name['node']._loaded_options = None
    _globals['_CREATENODEREQUEST'].fields_by_name['node']._serialized_options = b'\xe0A\x02'
    _globals['_DELETENODEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETENODEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node'
    _globals['_STOPNODEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_STOPNODEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node'
    _globals['_STARTNODEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_STARTNODEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node'
    _globals['_UPDATENODEREQUEST'].fields_by_name['update_mask']._loaded_options = None
    _globals['_UPDATENODEREQUEST'].fields_by_name['update_mask']._serialized_options = b'\xe0A\x02'
    _globals['_UPDATENODEREQUEST'].fields_by_name['node']._loaded_options = None
    _globals['_UPDATENODEREQUEST'].fields_by_name['node']._serialized_options = b'\xe0A\x02'
    _globals['_LISTQUEUEDRESOURCESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTQUEUEDRESOURCESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\x12!tpu.googleapis.com/QueuedResource'
    _globals['_GETQUEUEDRESOURCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETQUEUEDRESOURCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!tpu.googleapis.com/QueuedResource'
    _globals['_CREATEQUEUEDRESOURCEREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_CREATEQUEUEDRESOURCEREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_CREATEQUEUEDRESOURCEREQUEST'].fields_by_name['queued_resource']._loaded_options = None
    _globals['_CREATEQUEUEDRESOURCEREQUEST'].fields_by_name['queued_resource']._serialized_options = b'\xe0A\x02'
    _globals['_DELETEQUEUEDRESOURCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_DELETEQUEUEDRESOURCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!tpu.googleapis.com/QueuedResource'
    _globals['_RESETQUEUEDRESOURCEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_RESETQUEUEDRESOURCEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!tpu.googleapis.com/QueuedResource'
    _globals['_GENERATESERVICEIDENTITYREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_GENERATESERVICEIDENTITYREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\n!locations.googleapis.com/Location'
    _globals['_ACCELERATORTYPE']._loaded_options = None
    _globals['_ACCELERATORTYPE']._serialized_options = b'\xeaAq\n"tpu.googleapis.com/AcceleratorType\x12Kprojects/{project}/locations/{location}/acceleratorTypes/{accelerator_type}'
    _globals['_GETACCELERATORTYPEREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETACCELERATORTYPEREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA$\n"tpu.googleapis.com/AcceleratorType'
    _globals['_LISTACCELERATORTYPESREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTACCELERATORTYPESREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA$\x12"tpu.googleapis.com/AcceleratorType'
    _globals['_RUNTIMEVERSION']._loaded_options = None
    _globals['_RUNTIMEVERSION']._serialized_options = b'\xeaAn\n!tpu.googleapis.com/RuntimeVersion\x12Iprojects/{project}/locations/{location}/runtimeVersions/{runtime_version}'
    _globals['_GETRUNTIMEVERSIONREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETRUNTIMEVERSIONREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA#\n!tpu.googleapis.com/RuntimeVersion'
    _globals['_LISTRUNTIMEVERSIONSREQUEST'].fields_by_name['parent']._loaded_options = None
    _globals['_LISTRUNTIMEVERSIONSREQUEST'].fields_by_name['parent']._serialized_options = b'\xe0A\x02\xfaA#\x12!tpu.googleapis.com/RuntimeVersion'
    _globals['_GETGUESTATTRIBUTESREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_GETGUESTATTRIBUTESREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node'
    _globals['_SIMULATEMAINTENANCEEVENTREQUEST'].fields_by_name['name']._loaded_options = None
    _globals['_SIMULATEMAINTENANCEEVENTREQUEST'].fields_by_name['name']._serialized_options = b'\xe0A\x02\xfaA\x19\n\x17tpu.googleapis.com/Node'
    _globals['_ACCELERATORCONFIG'].fields_by_name['type']._loaded_options = None
    _globals['_ACCELERATORCONFIG'].fields_by_name['type']._serialized_options = b'\xe0A\x02'
    _globals['_ACCELERATORCONFIG'].fields_by_name['topology']._loaded_options = None
    _globals['_ACCELERATORCONFIG'].fields_by_name['topology']._serialized_options = b'\xe0A\x02'
    _globals['_BOOTDISKCONFIG'].fields_by_name['customer_encryption_key']._loaded_options = None
    _globals['_BOOTDISKCONFIG'].fields_by_name['customer_encryption_key']._serialized_options = b'\xe0A\x01'
    _globals['_BOOTDISKCONFIG'].fields_by_name['enable_confidential_compute']._loaded_options = None
    _globals['_BOOTDISKCONFIG'].fields_by_name['enable_confidential_compute']._serialized_options = b'\xe0A\x01'
    _globals['_TPU']._loaded_options = None
    _globals['_TPU']._serialized_options = b'\xcaA\x12tpu.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platform'
    _globals['_TPU'].methods_by_name['ListNodes']._loaded_options = None
    _globals['_TPU'].methods_by_name['ListNodes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x021\x12//v2alpha1/{parent=projects/*/locations/*}/nodes'
    _globals['_TPU'].methods_by_name['GetNode']._loaded_options = None
    _globals['_TPU'].methods_by_name['GetNode']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x021\x12//v2alpha1/{name=projects/*/locations/*/nodes/*}'
    _globals['_TPU'].methods_by_name['CreateNode']._loaded_options = None
    _globals['_TPU'].methods_by_name['CreateNode']._serialized_options = b'\xcaA\x19\n\x04Node\x12\x11OperationMetadata\xdaA\x13parent,node,node_id\x82\xd3\xe4\x93\x027"//v2alpha1/{parent=projects/*/locations/*}/nodes:\x04node'
    _globals['_TPU'].methods_by_name['DeleteNode']._loaded_options = None
    _globals['_TPU'].methods_by_name['DeleteNode']._serialized_options = b'\xcaA*\n\x15google.protobuf.Empty\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x021*//v2alpha1/{name=projects/*/locations/*/nodes/*}'
    _globals['_TPU'].methods_by_name['StopNode']._loaded_options = None
    _globals['_TPU'].methods_by_name['StopNode']._serialized_options = b'\xcaA\x19\n\x04Node\x12\x11OperationMetadata\x82\xd3\xe4\x93\x029"4/v2alpha1/{name=projects/*/locations/*/nodes/*}:stop:\x01*'
    _globals['_TPU'].methods_by_name['StartNode']._loaded_options = None
    _globals['_TPU'].methods_by_name['StartNode']._serialized_options = b'\xcaA\x19\n\x04Node\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02:"5/v2alpha1/{name=projects/*/locations/*/nodes/*}:start:\x01*'
    _globals['_TPU'].methods_by_name['UpdateNode']._loaded_options = None
    _globals['_TPU'].methods_by_name['UpdateNode']._serialized_options = b'\xcaA\x19\n\x04Node\x12\x11OperationMetadata\xdaA\x10node,update_mask\x82\xd3\xe4\x93\x02<24/v2alpha1/{node.name=projects/*/locations/*/nodes/*}:\x04node'
    _globals['_TPU'].methods_by_name['ListQueuedResources']._loaded_options = None
    _globals['_TPU'].methods_by_name['ListQueuedResources']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v2alpha1/{parent=projects/*/locations/*}/queuedResources'
    _globals['_TPU'].methods_by_name['GetQueuedResource']._loaded_options = None
    _globals['_TPU'].methods_by_name['GetQueuedResource']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v2alpha1/{name=projects/*/locations/*/queuedResources/*}'
    _globals['_TPU'].methods_by_name['CreateQueuedResource']._loaded_options = None
    _globals['_TPU'].methods_by_name['CreateQueuedResource']._serialized_options = b'\xcaA#\n\x0eQueuedResource\x12\x11OperationMetadata\xdaA)parent,queued_resource,queued_resource_id\x82\xd3\xe4\x93\x02L"9/v2alpha1/{parent=projects/*/locations/*}/queuedResources:\x0fqueued_resource'
    _globals['_TPU'].methods_by_name['DeleteQueuedResource']._loaded_options = None
    _globals['_TPU'].methods_by_name['DeleteQueuedResource']._serialized_options = b'\xcaA#\n\x0eQueuedResource\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02;*9/v2alpha1/{name=projects/*/locations/*/queuedResources/*}'
    _globals['_TPU'].methods_by_name['ResetQueuedResource']._loaded_options = None
    _globals['_TPU'].methods_by_name['ResetQueuedResource']._serialized_options = b'\xcaA#\n\x0eQueuedResource\x12\x11OperationMetadata\xdaA\x04name\x82\xd3\xe4\x93\x02D"?/v2alpha1/{name=projects/*/locations/*/queuedResources/*}:reset:\x01*'
    _globals['_TPU'].methods_by_name['GenerateServiceIdentity']._loaded_options = None
    _globals['_TPU'].methods_by_name['GenerateServiceIdentity']._serialized_options = b'\x82\xd3\xe4\x93\x02F"A/v2alpha1/{parent=projects/*/locations/*}:generateServiceIdentity:\x01*'
    _globals['_TPU'].methods_by_name['ListAcceleratorTypes']._loaded_options = None
    _globals['_TPU'].methods_by_name['ListAcceleratorTypes']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02<\x12:/v2alpha1/{parent=projects/*/locations/*}/acceleratorTypes'
    _globals['_TPU'].methods_by_name['GetAcceleratorType']._loaded_options = None
    _globals['_TPU'].methods_by_name['GetAcceleratorType']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02<\x12:/v2alpha1/{name=projects/*/locations/*/acceleratorTypes/*}'
    _globals['_TPU'].methods_by_name['ListRuntimeVersions']._loaded_options = None
    _globals['_TPU'].methods_by_name['ListRuntimeVersions']._serialized_options = b'\xdaA\x06parent\x82\xd3\xe4\x93\x02;\x129/v2alpha1/{parent=projects/*/locations/*}/runtimeVersions'
    _globals['_TPU'].methods_by_name['GetRuntimeVersion']._loaded_options = None
    _globals['_TPU'].methods_by_name['GetRuntimeVersion']._serialized_options = b'\xdaA\x04name\x82\xd3\xe4\x93\x02;\x129/v2alpha1/{name=projects/*/locations/*/runtimeVersions/*}'
    _globals['_TPU'].methods_by_name['GetGuestAttributes']._loaded_options = None
    _globals['_TPU'].methods_by_name['GetGuestAttributes']._serialized_options = b'\x82\xd3\xe4\x93\x02G"B/v2alpha1/{name=projects/*/locations/*/nodes/*}:getGuestAttributes:\x01*'
    _globals['_TPU'].methods_by_name['SimulateMaintenanceEvent']._loaded_options = None
    _globals['_TPU'].methods_by_name['SimulateMaintenanceEvent']._serialized_options = b'\xcaA\x19\n\x04Node\x12\x11OperationMetadata\x82\xd3\xe4\x93\x02M"H/v2alpha1/{name=projects/*/locations/*/nodes/*}:simulateMaintenanceEvent:\x01*'
    _globals['_GUESTATTRIBUTES']._serialized_start = 405
    _globals['_GUESTATTRIBUTES']._serialized_end = 512
    _globals['_GUESTATTRIBUTESVALUE']._serialized_start = 514
    _globals['_GUESTATTRIBUTESVALUE']._serialized_end = 600
    _globals['_GUESTATTRIBUTESENTRY']._serialized_start = 602
    _globals['_GUESTATTRIBUTESENTRY']._serialized_end = 671
    _globals['_ATTACHEDDISK']._serialized_start = 674
    _globals['_ATTACHEDDISK']._serialized_end = 843
    _globals['_ATTACHEDDISK_DISKMODE']._serialized_start = 775
    _globals['_ATTACHEDDISK_DISKMODE']._serialized_end = 843
    _globals['_SCHEDULINGCONFIG']._serialized_start = 845
    _globals['_SCHEDULINGCONFIG']._serialized_end = 902
    _globals['_NETWORKENDPOINT']._serialized_start = 904
    _globals['_NETWORKENDPOINT']._serialized_end = 1019
    _globals['_ACCESSCONFIG']._serialized_start = 1021
    _globals['_ACCESSCONFIG']._serialized_end = 1061
    _globals['_NETWORKCONFIG']._serialized_start = 1063
    _globals['_NETWORKCONFIG']._serialized_end = 1168
    _globals['_SERVICEACCOUNT']._serialized_start = 1170
    _globals['_SERVICEACCOUNT']._serialized_end = 1216
    _globals['_NODE']._serialized_start = 1219
    _globals['_NODE']._serialized_end = 3070
    _globals['_NODE_LABELSENTRY']._serialized_start = 2470
    _globals['_NODE_LABELSENTRY']._serialized_end = 2515
    _globals['_NODE_METADATAENTRY']._serialized_start = 2517
    _globals['_NODE_METADATAENTRY']._serialized_end = 2564
    _globals['_NODE_STATE']._serialized_start = 2567
    _globals['_NODE_STATE']._serialized_end = 2792
    _globals['_NODE_HEALTH']._serialized_start = 2794
    _globals['_NODE_HEALTH']._serialized_end = 2905
    _globals['_NODE_APIVERSION']._serialized_start = 2907
    _globals['_NODE_APIVERSION']._serialized_end = 2986
    _globals['_QUEUEDRESOURCE']._serialized_start = 3073
    _globals['_QUEUEDRESOURCE']._serialized_end = 4542
    _globals['_QUEUEDRESOURCE_TPU']._serialized_start = 3575
    _globals['_QUEUEDRESOURCE_TPU']._serialized_end = 3968
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC']._serialized_start = 3658
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC']._serialized_end = 3968
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC_MULTINODEPARAMS']._serialized_start = 3902
    _globals['_QUEUEDRESOURCE_TPU_NODESPEC_MULTINODEPARAMS']._serialized_end = 3968
    _globals['_QUEUEDRESOURCE_BESTEFFORT']._serialized_start = 3970
    _globals['_QUEUEDRESOURCE_BESTEFFORT']._serialized_end = 3982
    _globals['_QUEUEDRESOURCE_SPOT']._serialized_start = 3984
    _globals['_QUEUEDRESOURCE_SPOT']._serialized_end = 3990
    _globals['_QUEUEDRESOURCE_GUARANTEED']._serialized_start = 3992
    _globals['_QUEUEDRESOURCE_GUARANTEED']._serialized_end = 4081
    _globals['_QUEUEDRESOURCE_QUEUEINGPOLICY']._serialized_start = 4084
    _globals['_QUEUEDRESOURCE_QUEUEINGPOLICY']._serialized_end = 4407
    _globals['_QUEUEDRESOURCESTATE']._serialized_start = 4545
    _globals['_QUEUEDRESOURCESTATE']._serialized_end = 5851
    _globals['_QUEUEDRESOURCESTATE_CREATINGDATA']._serialized_start = 5424
    _globals['_QUEUEDRESOURCESTATE_CREATINGDATA']._serialized_end = 5438
    _globals['_QUEUEDRESOURCESTATE_ACCEPTEDDATA']._serialized_start = 5440
    _globals['_QUEUEDRESOURCESTATE_ACCEPTEDDATA']._serialized_end = 5454
    _globals['_QUEUEDRESOURCESTATE_PROVISIONINGDATA']._serialized_start = 5456
    _globals['_QUEUEDRESOURCESTATE_PROVISIONINGDATA']._serialized_end = 5474
    _globals['_QUEUEDRESOURCESTATE_FAILEDDATA']._serialized_start = 5476
    _globals['_QUEUEDRESOURCESTATE_FAILEDDATA']._serialized_end = 5523
    _globals['_QUEUEDRESOURCESTATE_DELETINGDATA']._serialized_start = 5525
    _globals['_QUEUEDRESOURCESTATE_DELETINGDATA']._serialized_end = 5539
    _globals['_QUEUEDRESOURCESTATE_ACTIVEDATA']._serialized_start = 5541
    _globals['_QUEUEDRESOURCESTATE_ACTIVEDATA']._serialized_end = 5553
    _globals['_QUEUEDRESOURCESTATE_SUSPENDINGDATA']._serialized_start = 5555
    _globals['_QUEUEDRESOURCESTATE_SUSPENDINGDATA']._serialized_end = 5571
    _globals['_QUEUEDRESOURCESTATE_SUSPENDEDDATA']._serialized_start = 5573
    _globals['_QUEUEDRESOURCESTATE_SUSPENDEDDATA']._serialized_end = 5588
    _globals['_QUEUEDRESOURCESTATE_STATE']._serialized_start = 5591
    _globals['_QUEUEDRESOURCESTATE_STATE']._serialized_end = 5763
    _globals['_QUEUEDRESOURCESTATE_STATEINITIATOR']._serialized_start = 5765
    _globals['_QUEUEDRESOURCESTATE_STATEINITIATOR']._serialized_end = 5837
    _globals['_LISTNODESREQUEST']._serialized_start = 5853
    _globals['_LISTNODESREQUEST']._serialized_end = 5959
    _globals['_LISTNODESRESPONSE']._serialized_start = 5961
    _globals['_LISTNODESRESPONSE']._serialized_end = 6074
    _globals['_GETNODEREQUEST']._serialized_start = 6076
    _globals['_GETNODEREQUEST']._serialized_end = 6139
    _globals['_CREATENODEREQUEST']._serialized_start = 6142
    _globals['_CREATENODEREQUEST']._serialized_end = 6309
    _globals['_DELETENODEREQUEST']._serialized_start = 6311
    _globals['_DELETENODEREQUEST']._serialized_end = 6397
    _globals['_STOPNODEREQUEST']._serialized_start = 6399
    _globals['_STOPNODEREQUEST']._serialized_end = 6463
    _globals['_STARTNODEREQUEST']._serialized_start = 6465
    _globals['_STARTNODEREQUEST']._serialized_end = 6530
    _globals['_UPDATENODEREQUEST']._serialized_start = 6532
    _globals['_UPDATENODEREQUEST']._serialized_end = 6657
    _globals['_LISTQUEUEDRESOURCESREQUEST']._serialized_start = 6659
    _globals['_LISTQUEUEDRESOURCESREQUEST']._serialized_end = 6785
    _globals['_LISTQUEUEDRESOURCESRESPONSE']._serialized_start = 6788
    _globals['_LISTQUEUEDRESOURCESRESPONSE']._serialized_end = 6932
    _globals['_GETQUEUEDRESOURCEREQUEST']._serialized_start = 6934
    _globals['_GETQUEUEDRESOURCEREQUEST']._serialized_end = 7017
    _globals['_CREATEQUEUEDRESOURCEREQUEST']._serialized_start = 7020
    _globals['_CREATEQUEUEDRESOURCEREQUEST']._serialized_end = 7229
    _globals['_DELETEQUEUEDRESOURCEREQUEST']._serialized_start = 7231
    _globals['_DELETEQUEUEDRESOURCEREQUEST']._serialized_end = 7352
    _globals['_RESETQUEUEDRESOURCEREQUEST']._serialized_start = 7354
    _globals['_RESETQUEUEDRESOURCEREQUEST']._serialized_end = 7439
    _globals['_SERVICEIDENTITY']._serialized_start = 7441
    _globals['_SERVICEIDENTITY']._serialized_end = 7473
    _globals['_GENERATESERVICEIDENTITYREQUEST']._serialized_start = 7475
    _globals['_GENERATESERVICEIDENTITYREQUEST']._serialized_end = 7566
    _globals['_GENERATESERVICEIDENTITYRESPONSE']._serialized_start = 7568
    _globals['_GENERATESERVICEIDENTITYRESPONSE']._serialized_end = 7663
    _globals['_ACCELERATORTYPE']._serialized_start = 7666
    _globals['_ACCELERATORTYPE']._serialized_end = 7904
    _globals['_GETACCELERATORTYPEREQUEST']._serialized_start = 7906
    _globals['_GETACCELERATORTYPEREQUEST']._serialized_end = 7991
    _globals['_LISTACCELERATORTYPESREQUEST']._serialized_start = 7994
    _globals['_LISTACCELERATORTYPESREQUEST']._serialized_end = 8156
    _globals['_LISTACCELERATORTYPESRESPONSE']._serialized_start = 8159
    _globals['_LISTACCELERATORTYPESRESPONSE']._serialized_end = 8306
    _globals['_RUNTIMEVERSION']._serialized_start = 8309
    _globals['_RUNTIMEVERSION']._serialized_end = 8471
    _globals['_GETRUNTIMEVERSIONREQUEST']._serialized_start = 8473
    _globals['_GETRUNTIMEVERSIONREQUEST']._serialized_end = 8556
    _globals['_LISTRUNTIMEVERSIONSREQUEST']._serialized_start = 8559
    _globals['_LISTRUNTIMEVERSIONSREQUEST']._serialized_end = 8719
    _globals['_LISTRUNTIMEVERSIONSRESPONSE']._serialized_start = 8722
    _globals['_LISTRUNTIMEVERSIONSRESPONSE']._serialized_end = 8866
    _globals['_OPERATIONMETADATA']._serialized_start = 8869
    _globals['_OPERATIONMETADATA']._serialized_end = 9083
    _globals['_SYMPTOM']._serialized_start = 9086
    _globals['_SYMPTOM']._serialized_end = 9417
    _globals['_SYMPTOM_SYMPTOMTYPE']._serialized_start = 9253
    _globals['_SYMPTOM_SYMPTOMTYPE']._serialized_end = 9417
    _globals['_GETGUESTATTRIBUTESREQUEST']._serialized_start = 9419
    _globals['_GETGUESTATTRIBUTESREQUEST']._serialized_end = 9533
    _globals['_GETGUESTATTRIBUTESRESPONSE']._serialized_start = 9535
    _globals['_GETGUESTATTRIBUTESRESPONSE']._serialized_end = 9633
    _globals['_SIMULATEMAINTENANCEEVENTREQUEST']._serialized_start = 9635
    _globals['_SIMULATEMAINTENANCEEVENTREQUEST']._serialized_end = 9735
    _globals['_ACCELERATORCONFIG']._serialized_start = 9738
    _globals['_ACCELERATORCONFIG']._serialized_end = 9904
    _globals['_ACCELERATORCONFIG_TYPE']._serialized_start = 9852
    _globals['_ACCELERATORCONFIG_TYPE']._serialized_end = 9904
    _globals['_SHIELDEDINSTANCECONFIG']._serialized_start = 9906
    _globals['_SHIELDEDINSTANCECONFIG']._serialized_end = 9958
    _globals['_BOOTDISKCONFIG']._serialized_start = 9961
    _globals['_BOOTDISKCONFIG']._serialized_end = 10107
    _globals['_CUSTOMERENCRYPTIONKEY']._serialized_start = 10109
    _globals['_CUSTOMERENCRYPTIONKEY']._serialized_end = 10163
    _globals['_TPU']._serialized_start = 10166
    _globals['_TPU']._serialized_end = 14164