
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-02T13:14:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "26607892b0e0926917f1012760508761da403973",
 "version": "1.31.0.post0.dev31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
