
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-02T10:14:24+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2316edf4b25bfc23dcc8abea665fa48066a04cf7",
 "version": "0.9.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
