
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-02T14:58:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "764c1557d810ed0c197da6084c9c18d621c35a7e",
 "version": "1.31.0.post0.dev43"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
