__built_time__        =  "built at Tue Dec 31 23:39:43 2024_CST"
__name__              =  "pyasd"
__version__           =  "0.0.37"
__author__            =  "Shunhong Zhang"
__author_email__      =  "zhangshunhong.pku@gmail.com"
__url__               =  "https://pypi.org/project/pyasd/"
__license__           =  "MIT LICENSE"
__platform__          =  "linux"
