# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/ads/googleads/v16/common/ad_asset.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'google/ads/googleads/v16/common/ad_asset.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.ads.googleads.v16.common import asset_policy_pb2 as google_dot_ads_dot_googleads_dot_v16_dot_common_dot_asset__policy__pb2
from google.ads.googleads.v16.enums import asset_performance_label_pb2 as google_dot_ads_dot_googleads_dot_v16_dot_enums_dot_asset__performance__label__pb2
from google.ads.googleads.v16.enums import served_asset_field_type_pb2 as google_dot_ads_dot_googleads_dot_v16_dot_enums_dot_served__asset__field__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.google/ads/googleads/v16/common/ad_asset.proto\x12\x1fgoogle.ads.googleads.v16.common\x1a\x32google/ads/googleads/v16/common/asset_policy.proto\x1a<google/ads/googleads/v16/enums/asset_performance_label.proto\x1a<google/ads/googleads/v16/enums/served_asset_field_type.proto\"\xd4\x02\n\x0b\x41\x64TextAsset\x12\x11\n\x04text\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x63\n\x0cpinned_field\x18\x02 \x01(\x0e\x32M.google.ads.googleads.v16.enums.ServedAssetFieldTypeEnum.ServedAssetFieldType\x12p\n\x17\x61sset_performance_label\x18\x05 \x01(\x0e\x32O.google.ads.googleads.v16.enums.AssetPerformanceLabelEnum.AssetPerformanceLabel\x12R\n\x13policy_summary_info\x18\x06 \x01(\x0b\x32\x35.google.ads.googleads.v16.common.AdAssetPolicySummaryB\x07\n\x05_text\",\n\x0c\x41\x64ImageAsset\x12\x12\n\x05\x61sset\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_asset\",\n\x0c\x41\x64VideoAsset\x12\x12\n\x05\x61sset\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_asset\"2\n\x12\x41\x64MediaBundleAsset\x12\x12\n\x05\x61sset\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_asset\"<\n\x1c\x41\x64\x44iscoveryCarouselCardAsset\x12\x12\n\x05\x61sset\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_asset\"3\n\x13\x41\x64\x43\x61llToActionAsset\x12\x12\n\x05\x61sset\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_assetB\xec\x01\n#com.google.ads.googleads.v16.commonB\x0c\x41\x64\x41ssetProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v16/common;common\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V16.Common\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V16\\Common\xea\x02#Google::Ads::GoogleAds::V16::Commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.ads.googleads.v16.common.ad_asset_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.google.ads.googleads.v16.commonB\014AdAssetProtoP\001ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v16/common;common\242\002\003GAA\252\002\037Google.Ads.GoogleAds.V16.Common\312\002\037Google\\Ads\\GoogleAds\\V16\\Common\352\002#Google::Ads::GoogleAds::V16::Common'
  _globals['_ADTEXTASSET']._serialized_start=260
  _globals['_ADTEXTASSET']._serialized_end=600
  _globals['_ADIMAGEASSET']._serialized_start=602
  _globals['_ADIMAGEASSET']._serialized_end=646
  _globals['_ADVIDEOASSET']._serialized_start=648
  _globals['_ADVIDEOASSET']._serialized_end=692
  _globals['_ADMEDIABUNDLEASSET']._serialized_start=694
  _globals['_ADMEDIABUNDLEASSET']._serialized_end=744
  _globals['_ADDISCOVERYCAROUSELCARDASSET']._serialized_start=746
  _globals['_ADDISCOVERYCAROUSELCARDASSET']._serialized_end=806
  _globals['_ADCALLTOACTIONASSET']._serialized_start=808
  _globals['_ADCALLTOACTIONASSET']._serialized_end=859
# @@protoc_insertion_point(module_scope)
