"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from exfunc import utils
from exfunc.types import BaseModel
from typing import Optional


class UserErrorData(BaseModel):
    message: Optional[str] = None
    r"""Error message string"""


class UserError(Exception):
    r"""User error response"""

    data: UserErrorData

    def __init__(self, data: UserErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, UserErrorData)
