
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-03T09:44:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "574b209846391d7b0833a3ac993f0df4e30da8ad",
 "version": "1.2.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
