
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-31T16:27:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d37e3183679ff4ab1e0afb510ca5cf1890752a8d",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
