from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="quantum_dot_sim", 
    version="1.1.1", 
    author="Arjun Skanda Ananda",
    author_email="arjunskanda@yahoo.com",  
    license="MIT",
    description="A package for simulating quantum dot behavior and analyzing energy levels, absorption spectra, and wavefunctions",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/ArjunSkanda/quantum_dot_sim", 
    packages=find_packages(), 
    include_package_data=True,
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7", 
    install_requires=[
        "absl-py==2.1.0",
        "astunparse==1.6.3",
        "certifi==2024.12.14",
        "gast==0.4.0",
        "charset-normalizer==3.4.0",
        "cloudpickle==3.1.0",
        "colorama==0.4.6",
        "contourpy==1.3.1",
        "cycler==0.12.1",
        "protobuf==3.20.3",
        "flatbuffers==24.3.25",
        "fonttools==4.55.3",
        "google-pasta==0.2.0",
        "grpcio==1.68.1",
        "h5py==3.12.1",
        "idna==3.10",
        "joblib==1.4.2",
        "keras==3.7.0",
        "kiwisolver==1.4.7",
        "libclang==18.1.1",
        "llvmlite==0.43.0",
        "Markdown==3.7",
        "markdown-it-py==3.0.0",
        "MarkupSafe==3.0.2",
        "matplotlib==3.10.0",
        "mdurl==0.1.2",
        "ml-dtypes==0.4.1",
        "namex==0.0.8",
        "numba==0.60.0",
        "numpy==2.0.2",
        "opt_einsum==3.4.0",
        "optree==0.13.1",
        "packaging==24.2",
        "pandas==2.2.3",
        "pillow==11.0.0",
        "plotly==5.24.1",
        "Pygments==2.18.0",
        "pyparsing==3.2.0",
        "python-dateutil==2.9.0.post0",
        "pytz==2024.2",
        "requests==2.32.3",
        "rich==13.9.4",
        "scikit-learn==1.6.0",
        "scipy==1.14.1",
        "shap==0.46.0",
        "six==1.17.0",
        "slicer==0.0.8",
        "tenacity==9.0.0",
        "tensorboard==2.18.0",
        "tensorboard-data-server==0.7.2",
        "tensorflow==2.18.0",
        "tensorflow-io-gcs-filesystem==0.31.0",
        "termcolor==2.5.0",
        "threadpoolctl==3.5.0",
        "tqdm==4.67.1",
        "typing_extensions==4.12.2",
        "tzdata==2024.2",
        "urllib3==2.2.3",
        "Werkzeug==3.1.3",
        "wrapt==1.17.0",
    ], 
    entry_points={
        "console_scripts": [
            "quantum-dot-sim=demo:main",
        ],
    },
)
