
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-30T15:58:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a23a603624017887f2a8cfe6721b7284a0ab8d7d",
 "version": "3.0alpha2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
