
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-19T16:32:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "914ab59309c4d45b12626ffc1c18e617d58b34ac",
 "version": "1.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
