
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-30T17:31:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd96faf10121579b84c28addcf89e556fd1b9627",
 "version": "0.1.1rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
