from pathlib import Path


Aero = str(Path(__file__).parent.absolute()) + "/aero.html"
Cerulean = str(Path(__file__).parent.absolute()) + "/cerulean.html"
Cosmo = str(Path(__file__).parent.absolute()) + "/cosmo.html"
Cyborg = str(Path(__file__).parent.absolute()) + "/cyborg.html"
Darkly = str(Path(__file__).parent.absolute()) + "/darkly.html"
Default = str(Path(__file__).parent.absolute()) + "/default.html"
Flatly = str(Path(__file__).parent.absolute()) + "/flatly.html"
Journal = str(Path(__file__).parent.absolute()) + "/journal.html"
Litera = str(Path(__file__).parent.absolute()) + "/litera.html"
Lumen = str(Path(__file__).parent.absolute()) + "/lumen.html"
Lux = str(Path(__file__).parent.absolute()) + "/lux.html"
Materia = str(Path(__file__).parent.absolute()) + "/materia.html"
Minty = str(Path(__file__).parent.absolute()) + "/minty.html"
Morph = str(Path(__file__).parent.absolute()) + "/morph.html"
Pulse = str(Path(__file__).parent.absolute()) + "/pulse.html"
Quartz = str(Path(__file__).parent.absolute()) + "/quartz.html"
Sandstone = str(Path(__file__).parent.absolute()) + "/sandstone.html"
Simplex = str(Path(__file__).parent.absolute()) + "/simplex.html"
Sketchy = str(Path(__file__).parent.absolute()) + "/sketchy.html"
Slate = str(Path(__file__).parent.absolute()) + "/slate.html"
Solar = str(Path(__file__).parent.absolute()) + "/solar.html"
Spacelab = str(Path(__file__).parent.absolute()) + "/spacelab.html"
Superhero = str(Path(__file__).parent.absolute()) + "/superhero.html"
United = str(Path(__file__).parent.absolute()) + "/united.html"
Vapor = str(Path(__file__).parent.absolute()) + "/vapor.html"
Yeti = str(Path(__file__).parent.absolute()) + "/yeti.html"
Zephyr = str(Path(__file__).parent.absolute()) + "/zephyr.html"


class InternalTemplates:
    JavaScript = str(Path(__file__).parent.absolute()) + "/Internal/dynamics.js"
    GeneralStyle = str(Path(__file__).parent.absolute()) + "/Internal/general.css"
    IconSample = str(Path(__file__).parent.absolute()) + "/Internal/iconsample.ico"
