from .blues import BLUES
from .browns import BROWNS
from .greens import GREENS
from .greys import GREYS
from .oranges import ORANGES
from .pinks import PINKS
from .purples import PURPLES
from .reds import REDS
from .whites import WHITES
from .yellows import YELLOWS
