# Generated by Django 5.1.4 on 2024-12-30 19:04

import autoparsed_address_field.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparsed_address_field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', autoparsed_address_field.fields.AutoParsedAddressField(on_delete=django.db.models.deletion.CASCADE, to='autoparsed_address_field.address')),
            ],
        ),
    ]
