
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-02T11:15:51-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1e6de9d9998839e4fc87d2f95f8853d36aef683a",
 "version": "0.15.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
