
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-04T17:27:16+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "8bcaaba944c5e5a6a41f1ab1be118a7a2053da1b",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
