
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-02T14:32:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bc167487609d5e486716f54d500299c4af2ad12",
 "version": "1.31.0.post0.dev40"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
