# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .actuator_line_model import ActuatorLineModel
from .blade_element_params import BladeElementParams


@dataclass(kw_only=True)
class ActuatorLineBladeElement(ActuatorLineModel):
    """Uses tables of airfoil aerodynamic data to model the effect of rotors and propellers"""

    blade_element_params: BladeElementParams = field(default_factory=BladeElementParams)
    ""
