# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .komega_boundary_conditions import KomegaBoundaryConditions


@dataclass(kw_only=True)
class BcTurbulentViscosityAndIntensityKomega(KomegaBoundaryConditions):
    """Set a uniform turbulent viscosity and turbulence intensity in the domain."""

    viscosity: float = 3.765582173541416e-06
    "Turbulent viscosity at the boundary."
    intensity: float = 0.05
    "Turbulence intensity at the boundary."
