# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .boussinesq_approximation import BoussinesqApproximation


@dataclass(kw_only=True)
class BoussinesqOn(BoussinesqApproximation):
    """Enable Boussinesq approximation."""

    reference_temperature: float = 288.15
    "Temperature at which there is no effect from the Boussinesq approximation (i.e. no change in density)."
    thermal_expansion_coefficient: float = 0.0035
    "Volumetric expansion due to temperature."
