# Generated by generate_sdk_wrappers.py. DO NOT EDIT

from abc import ABCMeta
from dataclasses import dataclass, field
from typing import Any, Optional
from uuid import uuid4

from luminarycloud.tables import RectilinearTable
from luminarycloud.types import Vector3
from luminarycloud._proto.client import simulation_pb2 as clientpb
from luminarycloud._proto.client.entity_pb2 import EntityIdentifier
import luminarycloud.params.enum._enum_wrappers as enum

from ._lib import ParamGroupWrapper, create_unique_id

from .time_step_ramp import TimeStepRamp


@dataclass(kw_only=True)
class TimeStepRampOn(TimeStepRamp):
    """Enable physical time step ramping."""

    inital_time_step: float = 0.001
    "Initial physical time step for time step ramping. The physical time step is ramped toward the target for the duration of the ramp."
    start_iteration: int = 500
    "Time step iteration to start the time step ramping process."
    end_iteration: int = 1000
    "Time step iteration to end the time step ramping process."
