use pyo3::prelude::*;
mod macros;

mod sampling;

/// Name of the root Python module generated by this Rust extension module.
const PYTHON_MODULE_NAME: &str = "oxidasim._rs";

#[pymodule]
fn _rs(m: &Bound<'_, PyModule>) -> PyResult<()> {
    sampling::register(m)?;
    Ok(())
}
