
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-02T12:48:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "19839813072b74d65db4fab32b0fe67282c0538d",
 "version": "1.31.0.post0.dev28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
